// Canolradd Vocabulary
const canolraddGlossary = {
"a bod yn onest": "to be honest",
  "aber": "estuary",
  "aberoedd": "estuaries",
  "absennol": "absent",
  "ac yn y blaen": "etc.",
  "achosi": "to cause",
  "adain": "wing",
  "adenydd": "wings",
  "adeg": "period of time",
  "adegau": "periods of time",
  "adnabyddus": "well-known",
  "adnewyddu": "to renew, to refurbish",
  "adran": "department",
  "adrannau": "departments",
  "adran cleifion allanol": "outpatients’ department",
  "adrodd": "to recite, to relate",
  "addasu": "to adapt",
  "addo": "to promise",
  "addurn": "decoration",
  "addurniadau": "decorations",
  "addysg": "education",
  "addysg gorfforol": "physical education",
  "aelod o’r senedd": "Member of the Senedd",
  "aelodau o’r senedd": "Members of the Senedd",
  "aelod seneddol": "Member of Parliament",
  "aelodau seneddol": "Members of Parliament",
  "afiach": "disgusting; sickly",
  "afiechyd": "disease",
  "afiechydon": "diseases",
  "agored": "open",
  "agoriad": "opening",
  "agoriadau": "openings",
  "agwedd": "attitude",
  "agweddau": "attitudes",
  "ailadrodd": "to repeat",
  "ailagor": "to reopen",
  "ailgylchu": "to recycle",
  "ail-law": "second-hand",
  "alergedd": "allergy",
  "allanfa": "exit",
  "allanfeydd": "exits",
  "amaethyddiaeth": "agriculture",
  "amaethyddol": "agricultural",
  "ambell": "a few",
  "amgylchedd": "environment",
  "amhosib": "impossible",
  "amlwg": "obvious, evident",
  "amrywiaeth": "variety, variation",
  "amrywiaethau": "varieties, variations",
  "amser maith yn ôl": "a long time ago",
  "amseru": "to time",
  "amynedd": "patience",
  "anadlu": "to breathe",
  "anaf": "injury",
  "anafiadau": "injuries",
  "anafu": "to injure",
  "anarferol": "unusual",
  "anfantais": "disadvantage",
  "anfanteision": "disadvantages",
  "anferth": "huge",
  "anffodus": "unfortunate",
  "angenrheidiol": "necessary",
  "anhapus": "unhappy",
  "anlwcus": "unlucky",
  "anniben": "untidy (South Wales)",
  "annifyr": "nasty, unpleasant",
  "annog": "to urge, to encourage",
  "apelio (at)": "to appeal (to)",
  "ar ddihun": "awake (South Wales)",
  "ar frys": "in a hurry",
  "ar glo": "locked",
  "ar gyhuddiad o": "accused of",
  "ar gyrion": "on the outskirts of",
  "ar hyd": "along",
  "ar hyd a lled": "the length and breadth (of)",
  "ar hyn o bryd": "at the moment",
  "ar lafar": "orally",
  "ar osod": "for rent",
  "ar ran": "on behalf of",
  "ar y blaen": "in the lead",
  "ar y cyfan": "on the whole",
  "ar y pryd": "at the time",
  "arbed": "to save",
  "archeb": "order",
  "archebion": "orders",
  "arddangos": "to exhibit",
  "arddangosfa": "exhibition",
  "arddangosfeydd": "exhibitions",
  "arestio": "to arrest",
  "arfer": "habit",
  "arferion": "habits",
  "arferol": "usual",
  "argraffu": "to print",
  "arlunydd": "artist",
  "arlunwyr": "artists",
  "arogl": "smell",
  "arogleuon": "smells",
  "arogli": "to smell",
  "arolwg": "review, survey",
  "arolygon": "reviews, surveys",
  "arolygydd": "inspector",
  "arolygwyr": "inspectors",
  "artist": "artist",
  "artistiaid": "artists",
  "arwain": "to lead",
  "arweinydd": "conductor, leader",
  "arweinyddion": "conductors, leaders",
  "arwr": "hero",
  "arwyr": "heroes",
  "arwydd": "sign",
  "arwyddion": "signs",
  "asgwrn": "bone",
  "esgyrn": "bones",
  "atgof": "memory, recollection",
  "atgofion": "memories, recollections",
  "atgoffa": "to remind",
  "athletau": "athletics",
  "awdurdod": "authority",
  "awdurdodau": "authorities",
  "awgrymu": "to suggest",
  "awyddus": "keen",
  "awyr iach": "fresh air",
  "bad achub": "lifeboat",
  "badau achub": "lifeboats",
  "bai": "blame, fault",
  "beiau": "faults",
  "bannau brycheiniog": "the Brecon Beacons",
  "bant": "away (South Wales)",
  "barnwr": "judge",
  "barnwyr": "judges",
  "basged": "basket",
  "basgedi": "baskets",
  "bat": "bat",
  "batiau": "bats",
  "baw": "dirt",
  "bawd": "thumb",
  "bodiau": "thumbs",
  "beiciwr": "cyclist",
  "beicwyr": "cyclists",
  "beirniad": "judge, adjudicator",
  "beirniaid": "judges, adjudicators",
  "beudy": "cowshed",
  "beudai": "cowsheds",
  "blas": "taste",
  "blasau": "tastes",
  "blasu": "to taste",
  "blinder": "tiredness",
  "blinedig": "tired",
  "blwch": "box",
  "blychau": "boxes",
  "blwyddyn naid": "leap year",
  "blynyddol": "annual",
  "bom": "bomb",
  "bomiau": "bombs",
  "botwm bol": "belly button",
  "breuddwyd": "dream",
  "breuddwydion": "dreams",
  "breuddwydio": "to dream",
  "bricsen": "brick",
  "brics": "bricks",
  "bro": "area, region",
  "broydd": "areas, regions",
  "bron": "breast, chest",
  "bronnau": "breasts, chests",
  "brwnt": "dirty (South Wales)",
  "bryd hynny": "at that time",
  "bryn": "hill",
  "bryniau": "hills",
  "bryste": "Bristol",
  "budr": "dirty (North Wales)",
  "busnes": "business",
  "busnesau": "businesses",
  "busneslyd": "meddlesome, nosy",
  "bwffe bys a bawd": "finger buffet",
  "bwlio": "to bully",
  "bwriadu": "to intend",
  "bwrw": "to hit (South Wales)",
  "bychan": "small",
  "bylb": "bulb",
  "bylbiau": "bulbs",
  "bys": "finger",
  "bysedd": "fingers",
  "bywiog": "lively",
  "cadair esmwyth": "easy chair",
  "cadeiriau esmwyth": "easy chairs",
  "cadair freichiau": "armchair",
  "cadeiriau breichiau": "armchairs",
  "cadarnhau": "to confirm",
  "cadeirio": "to chair",
  "cadeirydd": "chairperson",
  "cadeiryddion": "chairpersons",
  "cadw golwg ar": "to keep an eye on, to keep track of",
  "cadw sŵn": "to make a noise",
  "cael blas ar": "to enjoy",
  "cael gwared ar": "to get rid of",
  "cael hyd i": "to find, to discover",
  "caeredin": "Edinburgh",
  "caets": "cage",
  "caetsys": "cages",
  "calan mai": "May Day",
  "calendr": "calendar",
  "calendrau": "calendars",
  "cam": "step",
  "camau": "steps",
  "camera cyflymder": "speed camera",
  "camerâu cyflymder": "speed cameras",
  "camgymeriad": "mistake",
  "camgymeriadau": "mistakes",
  "canfed": "hundredth",
  "cangarŵ": "kangaroo",
  "cangarwod": "kangaroos",
  "cangen": "branch",
  "canghennau": "branches",
  "canlyniad": "result",
  "canlyniadau": "results",
  "cannwyll": "candle",
  "canhwyllau": "candles",
  "canolbarth": "middle part, region",
  "canser": "cancer",
  "canserau": "cancers",
  "canser y fron": "breast cancer",
  "cap": "cap",
  "capiau": "caps",
  "carchar": "prison",
  "carchardai": "prisons",
  "carcharu": "to imprison",
  "cariadus": "loving",
  "carreg": "stone",
  "cerrig": "stones",
  "carreg fedd": "gravestone",
  "cerrig beddau": "gravestones",
  "casgliad": "collection",
  "casgliadau": "collections",
  "catalog": "catalogue",
  "catalogau": "catalogues",
  "cawell": "cage",
  "cewyll": "cages",
  "cawr": "giant",
  "cewri": "giants",
  "caws gafr": "goats’ cheese",
  "cefndir": "background",
  "cefndiroedd": "backgrounds",
  "cefnogaeth": "support",
  "cefnogwr": "supporter",
  "cefnogwyr": "supporters",
  "celwydd": "lie",
  "celwyddau": "lies",
  "cemegyn": "chemical",
  "cemegau": "chemicals",
  "cenhinen": "leek",
  "cennin": "leeks",
  "cerbyd": "vehicle",
  "cerbydau": "vehicles",
  "cerdd": "poem",
  "cerddi": "poems",
  "cerddorfa": "orchestra",
  "cerddorfeydd": "orchestras",
  "cicio": "to kick",
  "claf": "patient",
  "cleifion": "patients",
  "clebran": "to chatter",
  "clo": "lock",
  "cloeon": "locks",
  "cloch": "bell",
  "clychau": "bells",
  "clogwyn": "cliff",
  "clogwyni": "cliffs",
  "clonc": "chat (South Wales)",
  "cludo": "to transport",
  "clustog": "cushion",
  "clustogau": "cushions",
  "clwt": "cloth, rag",
  "clwtyn": "cloth, rag",
  "clytiau": "cloths, rags",
  "clyfar": "clever",
  "clymu": "to tie, to knot",
  "cneuen": "nut",
  "cnau": "nuts",
  "cneuen goco": "coconut",
  "cnau coco": "coconuts",
  "cochi": "to blush",
  "codi llaw (ar)": "to wave (to)",
  "codi ofn (ar)": "to frighten",
  "codi pwysau": "weightlifting",
  "cof": "memory",
  "cofeb": "memorial",
  "cofebau": "memorials",
  "cofnod": "note, written record, minutes",
  "cofnodion": "notes, written records, minutes",
  "colur": "make-up",
  "colled": "loss",
  "colledion": "losses",
  "colli gafael (ar)": "to lose hold of",
  "copa": "summit",
  "copaon": "summits",
  "copi": "copy",
  "copïau": "copies",
  "corff": "body",
  "cyrff": "bodies",
  "coroni": "to crown",
  "cors": "bog",
  "corsydd": "bogs",
  "cosi": "to itch",
  "costus": "pricey",
  "cotwm": "cotton",
  "cownter": "counter",
  "cownteri": "counters",
  "craith": "scar",
  "creithiau": "scars",
  "crand": "grand",
  "creadigol": "creative",
  "crefft": "craft",
  "crefftau": "crafts",
  "creu": "to create",
  "cribo": "to comb",
  "cricedwr": "cricketer",
  "cricedwyr": "cricketers",
  "criw": "crew",
  "criwiau": "crews",
  "croes": "cross",
  "croesau": "crosses",
  "croesawu": "to welcome",
  "croesffordd": "crossroad",
  "croesffyrdd": "crossroads",
  "croesi": "to cross",
  "crud": "cradle, cot",
  "crudau": "cradles, cots",
  "crwn": "round",
  "crwydro": "to wander, to roam",
  "cryfder": "strength",
  "cryfderau": "strengths",
  "cul": "narrow",
  "curo": "to beat",
  "curo dwylo": "to clap, to applaud",
  "curo’r drws": "to knock the door",
  "cwblhau": "to complete",
  "cwlwm": "knot",
  "clymau": "knots",
  "cwr": "edge, fringe",
  "cyrion": "edges, fringes",
  "cwrtais": "courteous, polite",
  "cwsg": "sleep",
  "cwt gwair": "hay hut",
  "cytiau gwair": "hay huts",
  "cwt ieir": "hen coop",
  "cytiau ieir": "hen coops",
  "cwyn": "complaint",
  "cwynion": "complaints",
  "cydio": "to hold on (to)",
  "cyfaill": "friend",
  "cyfeillion": "friends",
  "cyfanswm": "total",
  "cyfansymiau": "totals",
  "cyfarch": "to greet",
  "cyfartal": "equal",
  "cyfarwyddyd": "direction, instruction",
  "cyfarwyddiadau": "directions, instructions",
  "cyfathrebu": "to communicate",
  "cyfleuster": "facility",
  "cyfleusterau": "facilities",
  "cyflog": "wage, salary",
  "cyflogau": "wages, salaries",
  "cyflogi": "to employ",
  "cyflwyno": "to introduce, to present",
  "cyfnewid": "to exchange",
  "cyfnod": "period (time)",
  "cyfnodau": "periods (time)",
  "cyfoes": "contemporary",
  "cyfoeth": "wealth",
  "cyfraith": "law",
  "cyfreithiau": "laws",
  "cyfrannu": "to contribute (to)",
  "cyfres": "series",
  "cyfresi": "series",
  "cyfrif": "account",
  "cyfrifon": "accounts",
  "cyfrifol": "responsible",
  "cyfrifydd": "accountant",
  "cyfrifwyr": "accountants",
  "cyfrinach": "secret",
  "cyfrinachau": "secrets",
  "cyfwelydd": "interviewer",
  "cyfwelwyr": "interviewers",
  "cyffordd": "junction",
  "cyffyrdd": "junctions",
  "cyfforddus": "comfortable",
  "cyffredin": "common, general",
  "cyffro": "excitement",
  "cyffroi": "to excite",
  "cyffur": "drug",
  "cyffuriau": "drugs",
  "cynghori": "to advise",
  "cynghorydd": "councillor",
  "cynghorwyr": "councillors",
  "cyhoeddus": "public",
  "cyhuddiad": "charge, accusation",
  "cyhuddiadau": "charges, accusations",
  "cylch": "circle",
  "cylchoedd": "circles",
  "cylch chwarae": "playgroup",
  "cymar": "partner, companion",
  "cymdeithas": "society",
  "cymdeithasau": "societies",
  "cymdeithasol": "social, sociable",
  "cymhleth": "complicated",
  "cymorth": "help",
  "cymorth cyntaf": "first aid",
  "cymuned": "community",
  "cymunedau": "communities",
  "cymwynas": "favour",
  "cymwynasau": "favours",
  "cymysgu": "to mix (with)",
  "cynhesu": "to heat up",
  "cynllun": "plan, design",
  "cynlluniau": "plans, designs",
  "cynllunio": "to plan, to design",
  "cynnal": "to hold (event)",
  "cynnal a chadw": "maintenance",
  "cyntedd": "hallway",
  "cynteddau": "hallways",
  "cynulleidfa": "audience",
  "cynulleidfaoedd": "audiences",
  "cysgod": "shadow, shade",
  "cysgodion": "shadows, shades",
  "cyswllt": "contact",
  "cywir": "correct",
  "chwant bwyd": "food craving",
  "chwarel": "quarry",
  "chwareli": "quarries",
  "chwedl": "legend",
  "chwedlau": "legends",
  "chwerthin am ben": "to laugh at",
  "chwynnu": "to weed",
  "dadlau": "to argue (with)",
  "daear": "earth",
  "dal ati": "to keep at it, to persevere",
  "dan bwysau": "under pressure",
  "dan ei sang": "full to the rafters",
  "dant gosod": "false tooth",
  "dannedd gosod": "false teeth",
  "darlith": "lecture",
  "darlithoedd": "lectures",
  "darlun": "drawing",
  "darluniau": "drawings",
  "dawn": "talent",
  "doniau": "talents",
  "dealltwriaeth": "understanding",
  "deallus": "intelligent",
  "defnydd": "use",
  "defnyddiol": "useful",
  "deiet": "diet",
  "deigryn": "tear",
  "dagrau": "tears",
  "delio (â/efo)": "to deal (with)",
  "deniadol": "attractive",
  "derbyn": "to accept, to receive",
  "desg": "desk",
  "desgiau": "desks",
  "diamynedd": "impatient",
  "dianc": "to escape",
  "dieithr": "strange",
  "dieuog": "innocent, not guilty",
  "diflannu": "to disappear",
  "diflastod": "boredom",
  "difrifol": "serious",
  "difrod": "damage",
  "difyr": "entertaining",
  "diffyg": "shortcoming, lack of",
  "diffygion": "shortcomings, lack of",
  "digalon": "depressed, depressing",
  "digwyddiad": "event, incident",
  "digwyddiadau": "events, incidents",
  "di-gymraeg": "non-Welsh speaking",
  "dinistrio": "to destroy",
  "dioddef": "to suffer",
  "diogel": "safe",
  "diogelwch": "safety",
  "diogi": "to laze",
  "di-ri(f)": "countless",
  "distawrwydd": "silence",
  "diweithdra": "unemployment",
  "diwydiant": "industry",
  "diwydiannau": "industries",
  "diwylliant": "culture",
  "diwylliannau": "cultures",
  "dod draw": "to come over",
  "dod i ben": "to come to an end",
  "dod o hyd i": "to find",
  "dodrefnyn": "piece of furniture",
  "dodrefn": "furniture",
  "dolen": "loop, link, handle",
  "dolenni": "loops, links, handles",
  "draenen ddu": "blackthorn",
  "drewi": "to stink",
  "dril": "drill",
  "driliau": "drills",
  "dringwr": "climber",
  "dringwyr": "climbers",
  "drosodd": "over, overleaf",
  "druan â ti": "poor you (South Wales)",
  "druan ohonat ti": "poor you (North Wales)",
  "drws ffrynt": "front door",
  "drysau ffrynt": "front doors",
  "drych": "mirror",
  "drychau": "mirrors",
  "dur": "steel",
  "dwbl": "double",
  "dweud eich dweud": "to have your say (South Wales)",
  "deud eich deud": "to have your say (North Wales)",
  "dwfn": "deep",
  "dwyieithog": "bilingual",
  "dwys": "intense, intensive",
  "dychrynllyd": "frightening",
  "dydd ffolant": "Valentine’s day",
  "dyddiad cau": "closing date",
  "dyddiol": "daily",
  "dyffryn": "valley",
  "dyffrynnoedd": "valleys",
  "dyled": "debt",
  "dyledion": "debts",
  "economaidd": "economic, economical",
  "economi": "economy",
  "edrych dros": "to check, to look over",
  "efaill": "twin",
  "efeilliaid": "twins",
  "efrog newydd": "New York",
  "efydd": "bronze",
  "effeithio (ar)": "to affect",
  "eglur": "evident, clear",
  "egluro": "to explain",
  "eglwys gadeiriol": "cathedral",
  "eglwysi cadeiriol": "cathedrals",
  "egni": "energy",
  "eirlaw": "sleet",
  "eirlys": "snowdrop",
  "eirlysiau": "snowdrops",
  "electronig": "electronic",
  "enfys": "rainbow",
  "enfysau": "rainbows",
  "enwi": "to name",
  "er": "although",
  "er gwaetha": "despite",
  "erthygl": "article",
  "erthyglau": "articles",
  "esboniad": "explanation",
  "esboniadau": "explanations",
  "esgus": "excuse",
  "esgusodion": "excuses",
  "esiampl": "example",
  "esiamplau": "examples",
  "esmwyth": "restful, smooth",
  "estyniad": "extension",
  "estyniadau": "extensions",
  "etholiad": "election",
  "etholiadau": "elections",
  "eto i gyd": "even so",
  "euog": "guilty",
  "ewyn": "foam",
  "feirws": "virus",
  "feirysau": "viruses",
  "fesul un": "one by one",
  "ficer": "vicar",
  "ficeriaid": "vicars",
  "figan": "vegan",
  "figaniaid": "vegans",
  "ffaith": "fact",
  "ffeithiau": "facts",
  "ffarwelio": "to say goodbye (to)",
  "fferyllydd": "chemist",
  "fferllywyr": "chemists",
  "ffeuen": "bean",
  "ffa": "beans",
  "ffidil": "violin",
  "ffidlau": "violins",
  "ffilmio": "to film",
  "ffin": "border",
  "ffiniau": "borders",
  "ffitrwydd": "fitness",
  "fflam": "flame",
  "fflamau": "flames",
  "ffoadur": "refugee",
  "ffoaduriaid": "refugees",
  "ffodus": "fortunate",
  "ffon": "stick",
  "ffyn": "sticks",
  "ffrâm": "frame",
  "fframiau": "frames",
  "ffrwydro": "to explode",
  "ffurflen gais": "application form",
  "ffurflenni cais": "application forms",
  "ffyrnig": "fierce",
  "galluog": "capable, brainy",
  "gan gynnwys": "including",
  "gefeillio": "to twin",
  "gêm gyfartal": "a draw",
  "gemau olympaidd": "Olympic Games",
  "genedigaeth": "birth",
  "genedigaethau": "births",
  "genedigol": "native",
  "glan": "shore, bank",
  "glannau": "shores, banks",
  "glaw mân": "drizzle",
  "gliniadur": "laptop",
  "gliniaduron": "laptops",
  "go iawn": "real",
  "gofal": "care",
  "gofalwr": "carer, caretaker",
  "gofalwyr": "carers, caretakers",
  "gofod": "space",
  "goleudy": "lighthouse",
  "goleudai": "lighthouses",
  "golygu": "to mean, to edit",
  "gollwng": "to drop",
  "gorffwys": "rest",
  "gorlifo": "to overflow",
  "gorwedd": "to lie down",
  "gorwel": "horizon",
  "gorwelion": "horizons",
  "gosod": "to set, to put",
  "gostyngiad": "reduction",
  "gostyngiadau": "reductions",
  "gradd feistr": "master’s degree",
  "graddio": "to graduate",
  "gramadeg": "grammar",
  "grawnwinen": "grape",
  "grawnwin": "grapes",
  "grefi": "gravy",
  "gwadu": "to deny",
  "gwahaniaeth": "difference",
  "gwahaniaethau": "differences",
  "gwall": "error",
  "gwallau": "errors",
  "gwasanaethu": "to serve",
  "gwasg": "printing press",
  "gweisg": "printing presses",
  "gwasgu": "to squeeze, to squash",
  "gwastad": "flat",
  "gwastraff": "waste",
  "gwastraffu": "to waste",
  "gwau": "to knit (South Wales)",
  "gwefus": "lip",
  "gwefusau": "lips",
  "gweini": "to serve",
  "gweithgar": "hardworking",
  "gweithgaredd": "activity",
  "gweithgareddau": "activities",
  "gweithle": "workplace",
  "gweithleoedd": "workplaces",
  "gwell hwyr na hwyrach": "better late than never",
  "gwên": "smile",
  "gwenau": "smiles",
  "gwerin": "folk",
  "gwerthfawr": "valuable",
  "gwestai": "guest",
  "gwesteion": "guests",
  "gweu": "to knit (North Wales)",
  "gwibdaith": "trip, excursion",
  "gwibdeithiau": "trips, excursions",
  "gwlân": "wool",
  "gwleidyddiaeth": "politics",
  "gwlychu": "to get wet",
  "gwm": "gum",
  "gwm cnoi": "chewing gum",
  "gwneud cawl o": "to make a mess of (South Wales)",
  "gwneud llanast o": "to make a mess of (North Wales)",
  "gwneud y tro": "to make do, to answer the purpose",
  "gwrach": "witch",
  "gwrachod": "witches",
  "gwraidd": "root",
  "gwreiddiau": "roots",
  "gwrandäwr": "listener",
  "gwrandawyr": "listeners",
  "gwthio": "to push",
  "gwyddel": "Irish man",
  "gwyddelod": "Irish people",
  "gwyddeles": "Irish woman",
  "gwylan": "seagull",
  "gwylanod": "seagulls",
  "gwyllt": "wild",
  "gyda llaw": "by the way",
  "gyda’r hwyr": "in the night",
  "gymnasteg": "gymnastics",
  "hael": "generous",
  "hallt": "salty",
  "hamddenol": "leisurely",
  "hanesydd": "historian",
  "haneswyr": "historians",
  "hanesyddol": "historical",
  "hapusrwydd": "happiness",
  "hawlio": "to claim",
  "heblaw am": "apart from",
  "hel atgofion": "to reminisce",
  "hen dad-cu": "great-grandfather",
  "hen daid": "great-grandfather",
  "hen fam-gu": "great-grandmother",
  "hen nain": "great-grandmother",
  "henaint": "old age",
  "heneiddio": "to age",
  "henoed": "elderly people",
  "heulwen": "sunshine",
  "hirgrwn": "oval",
  "hoffus": "likeable",
  "holiadur": "questionnaire",
  "holiaduron": "questionnaires",
  "hollbwysig": "all-important",
  "hwyliog": "full of fun",
  "hwylus": "convenient",
  "hyd yn hyn": "up until now",
  "hyder": "confidence",
  "hynny": "that",
  "i fod i": "supposed to",
  "i’r dim": "exactly",
  "iachus": "healthy (food)",
  "iard": "yard",
  "iardiau": "yards",
  "iechyd a diogelwch": "health and safety",
  "Iesu": "Jesus",
  "ieuenctid": "youth",
  "injan dân": "fire engine",
  "injans tân": "fire engines",
  "isod": "beneath, below",
  "jyngl": "jungle",
  "jyngls": "jungles",
  "lansio": "to launch",
  "lapio": "to wrap",
  "lawr grisiau": "downstairs (North Wales)",
  "lawr llawr": "downstairs (South Wales)",
  "lefel": "level",
  "lefelau": "levels",
  "lolipop": "lollypop",
  "lolipops": "lollypops",
  "lôn feicio": "bike lane",
  "lonydd beicio": "bike lanes",
  "lwcus": "lucky",
  "lladd": "to kill",
  "lladrad": "burglary",
  "lladradau": "burglaries",
  "llafar": "oral",
  "llanast": "mess (North Wales)",
  "llanc": "lad, youth",
  "llanciau": "lads, youth",
  "llanw a thrai": "tides; ebb and flow",
  "llawdriniaeth": "operation",
  "llawdriniaethau": "operations",
  "llawr gwaelod": "ground floor",
  "lle tân": "fireplace",
  "llefydd tân": "fireplaces",
  "lledr": "leather",
  "lledu": "to spread, to widen",
  "llefarydd": "spokesperson",
  "llefarwyr": "spokespeople",
  "lleidr": "thief",
  "lladron": "thieves",
  "lleihau": "to reduce",
  "llenyddiaeth": "literature",
  "lleoliad": "location",
  "lleoliadau": "locations",
  "llethr": "slope",
  "llethrau": "slopes",
  "llety": "accommodation",
  "llewygu": "to faint",
  "llif": "flood",
  "llifogydd": "floods",
  "llifo": "to flow",
  "llithrig": "slippery",
  "llithro": "to slip",
  "lloches": "shelter",
  "llochesau": "shelters",
  "llond bol": "bellyful (fed up) (North Wales)",
  "llond bola": "bellyful (fed up) (South Wales)",
  "lluosog": "plural",
  "lluosogion": "plurals",
  "llwch": "dust",
  "llwy garu": "lovespoon",
  "llwyau caru": "lovespoons",
  "llwyaid": "spoonful",
  "llwyeidiau": "spoonfuls",
  "llwyddiannus": "successful",
  "llwyddiant": "success",
  "llwyddiannau": "successes",
  "llwyddo (i)": "to succeed (in)",
  "llwyfan": "stage",
  "llwyfannau": "stages",
  "llwyth": "load",
  "llwythi": "loads",
  "llydan": "wide",
  "llyfr gosod": "set book",
  "llyfrau gosod": "set books",
  "llym": "severe",
  "llyn": "lake",
  "llynnoedd": "lakes",
  "llyncu": "to swallow",
  "llys": "court",
  "llysoedd": "courts",
  "llywodraeth": "government",
  "llywodraethau": "governments",
  "machlud": "sunset",
  "maer": "mayor",
  "meiri": "mayors",
  "man": "place",
  "mannau": "places",
  "mân siarad": "chit-chat",
  "mantais": "advantage",
  "manteision": "advantages",
  "manwl": "detailed",
  "manylion personol": "personal details",
  "marc": "mark",
  "marciau": "marks",
  "marchnata": "marketing",
  "marcio": "to mark",
  "marwolaeth": "death",
  "marwolaethau": "deaths",
  "medal": "medal",
  "medalau": "medals",
  "meddal": "soft",
  "meddyginiaeth": "medication",
  "meddyginiaethau": "medications",
  "mellten": "lightning",
  "mellt": "flashes of lightning",
  "menter": "venture, initiative",
  "mentrau": "ventures, initiatives",
  "mentro": "to venture, to dare",
  "mentrus": "adventurous",
  "mesur": "to measure",
  "metel": "metal",
  "metelau": "metals",
  "mewn gwirionedd": "in truth",
  "modern": "modern",
  "moethus": "luxurious",
  "mordaith": "cruise",
  "mordeithiau": "cruises",
  "morwyn": "maid",
  "morwynion": "maids",
  "mudiad": "movement, organisation",
  "mudiadau": "movements, organisations",
  "murlun": "mural",
  "murluniau": "murals",
  "mwd": "mud",
  "mwdlyd": "muddy",
  "mwg": "smoke",
  "mwynhad": "enjoyment",
  "mynnu": "to insist",
  "mynwent": "graveyard, cemetery",
  "mynwentydd": "graveyards, cemeteries",
  "nant": "stream, creek",
  "nentydd": "streams, creeks",
  "nefoedd": "heaven",
  "neidio": "to jump",
  "nerfus": "nervous",
  "nerth": "strength",
  "newid mân": "small change",
  "newydd sbon": "brand new",
  "nifer": "number, quantity",
  "niferoedd": "numbers, quantities",
  "nodyn": "note",
  "nodiadau": "notes",
  "nyth": "nest",
  "nythod": "nests",
  "o amgylch": "around",
  "o bell": "from afar",
  "o ddifri": "seriously",
  "o ddrwg i waeth": "from bad to worse",
  "o dro i dro": "from time to time",
  "o fewn": "within",
  "o flaen": "in front of",
  "o hyn ymlaen": "from now on",
  "o leia": "at least",
  "o’r enw": "named, called",
  "obsesiwn": "obsession",
  "obsesiynau": "obsessions",
  "ocsiwn": "auction",
  "ocsiynau": "auctions",
  "od": "odd",
  "oddi ar": "from (on), off, down from",
  "oddi cartre": "away from home",
  "oedi": "to pause, to delay",
  "oedran": "age",
  "oedrannau": "ages",
  "oerfel": "cold (weather)",
  "oesoedd canol": "middle ages",
  "ofni": "to fear",
  "ofnus": "fearful, frightened",
  "oherwydd": "because",
  "oni bai am": "if it weren’t for",
  "oriau mân": "small hours",
  "oriel": "gallery",
  "orielau": "galleries",
  "osgoi": "to avoid",
  "paith": "prairie",
  "peithiau": "prairies",
  "palmant": "pavement",
  "palmentydd": "pavements",
  "para": "to last",
  "parc gwledig": "country park",
  "parciau gwledig": "country parks",
  "parch": "respect",
  "parhau": "to continue",
  "partner": "partner",
  "partneriaid": "partners",
  "patrwm": "pattern",
  "patrymau": "patterns",
  "pecyn": "package",
  "pecynnau": "packages",
  "peldroediwr": "footballer",
  "peldroedwyr": "footballers",
  "pellter": "distance",
  "pellteroedd": "distances",
  "pen draw": "far end, long run",
  "pencampwriaeth": "championship",
  "pencampwriaethau": "championships",
  "pendant": "definite",
  "penderfyniad": "decision",
  "penderfyniadau": "decisions",
  "pennawd": "headline",
  "penawdau": "headlines",
  "penodi": "to appoint",
  "perchennog": "owner",
  "perchnogion": "owners",
  "personoliaeth": "personality",
  "personoliaethau": "personalities",
  "perswadio": "to persuade",
  "perygl": "danger",
  "peryglon": "dangers",
  "petryal": "rectangular",
  "pibell": "pipe",
  "pibelli": "pipes",
  "pigiad": "injection",
  "pigiadau": "injections",
  "plaid": "political party",
  "pleidiau": "political parties",
  "plannu": "to plant",
  "plentyndod": "childhood",
  "pleser": "pleasure",
  "pleserau": "pleasures",
  "pleserus": "enjoyable",
  "plygu": "to fold, to bend",
  "pob dim": "everything",
  "poblogaidd": "popular",
  "polisi": "policy",
  "polisïau": "policies",
  "pori": "to graze, to browse",
  "poster": "poster",
  "posteri": "posters",
  "prancio": "to prance, to gambol",
  "preifat": "private",
  "presgripsiwn": "prescription",
  "presgripsiynau": "prescriptions",
  "pridd": "earth, soil",
  "prif weinidog": "Prime Minister",
  "priffordd": "main road",
  "priffyrdd": "main roads",
  "prin": "rare, scarce",
  "proffesiwn": "profession",
  "proffesiynau": "professions",
  "proffesiynol": "professional",
  "profiadol": "experienced",
  "project": "project",
  "projectau": "projects",
  "proses": "process",
  "prosesau": "processes",
  "protestio": "to protest",
  "protestiwr": "protester",
  "protestwyr": "protesters",
  "prydeiniwr": "a man from Britain",
  "prydeinwyr": "British people",
  "prydeinwraig": "a woman from Britain",
  "prydferthwch": "beauty",
  "prydlon": "punctual, prompt",
  "pur": "pure",
  "pŵer": "power",
  "pwerau": "powers",
  "pwnc": "subject",
  "pynciau": "subjects",
  "pwrpas": "purpose",
  "pwrpasau": "purposes",
  "pwyllgor": "committee",
  "pwyllgorau": "committees",
  "pwyntiau bwled": "bullet points",
  "pwyntio": "to point",
  "pwysleisio": "to emphasise",
  "pwyso": "to press, to weigh",
  "raced": "racket",
  "racedi": "rackets",
  "raftio": "to raft",
  "rasio": "to race",
  "recordio": "to record",
  "regata": "regata",
  "regatas": "regattas",
  "roced": "rocket",
  "rocedi": "rockets",
  "rhaff": "rope",
  "rhaffau": "ropes",
  "rhagor": "more",
  "rhagorol": "excellent",
  "rhamantus": "romantic",
  "rhaw": "spade",
  "rhawiau": "spades",
  "rhedwr": "runner",
  "rhedwyr": "runners",
  "rhentu": "to rent",
  "rheol": "rule",
  "rheolau": "rules",
  "rhes": "row",
  "rhesi": "rows",
  "rhewllyd": "icy",
  "rhiant maeth": "foster parent",
  "rhieni maeth": "foster parents",
  "rhifo": "to count, to calculate",
  "rhoi’r gorau i": "to give up",
  "rhos": "heath, moor",
  "rhosydd": "heaths, moors",
  "rhostio": "to roast",
  "rhufeiniaid": "the Romans",
  "rhuthro": "to rush",
  "rhwyd": "net",
  "rhwydi": "nets",
  "rhwystr": "obstacle",
  "rhwystrau": "obstacles",
  "rhwystro": "to prevent",
  "rhybudd": "warning",
  "rhybuddion": "warnings",
  "rhybuddio": "to warn",
  "rhyddhau": "to free",
  "rhyfel": "war",
  "rhyfeloedd": "wars",
  "rhyw": "sex",
  "rhywiau": "sexes",
  "rhywbeth o’i le": "something wrong",
  "saethu": "to shoot",
  "safbwynt": "stance, viewpoint",
  "safbwyntiau": "stances, viewpoints",
  "safle": "site, position",
  "safleoedd": "sites, positions",
  "safon": "standard",
  "safonau": "standards",
  "saws": "sauce",
  "sawsiau": "sauces",
  "sbeis": "spice",
  "sbeisys": "spices",
  "sbio": "to look (North Wales)",
  "sbort a sbri": "fun and games",
  "sefydliad": "institution, establishment, institute",
  "sefydliadau": "institutions, establishments, institutes",
  "sefydlog": "stable, fixed, unchanging",
  "sefydlu": "to establish",
  "sefyllfa": "situation",
  "sefyllfaoedd": "situations",
  "seiclwr": "cyclist",
  "seiclwyr": "cyclists",
  "sengl": "single",
  "serch": "romantic love",
  "serth": "steep",
  "sgerbwd": "skeleton",
  "sgerbydau": "skeletons",
  "sgwâr": "square",
  "sgwariau": "squares",
  "siâp": "shape",
  "siapiau": "shapes",
  "siaradus": "talkative",
  "siawns": "chance",
  "siawnsiau": "chances",
  "sibrwd": "to whisper",
  "sidan": "silk",
  "siglo": "to rock, to shake",
  "sioc": "shock",
  "siociau": "shocks",
  "siop trin gwallt": "hairdressers’ shop",
  "siswrn": "scissors",
  "sisyrnau": "scissors",
  "sleifio": "to slink, to sneak, to sidle",
  "smotiog": "spotty",
  "snorclo": "to snorkel",
  "soffa": "sofa",
  "soffas": "sofas",
  "sownd": "stuck",
  "staffio": "to staff",
  "steil": "style",
  "stordy": "storehouse",
  "stordai": "storehouses",
  "storio": "to store",
  "streic": "strike",
  "streiciau": "strikes",
  "streiciwr": "striker (work)",
  "streicwyr": "strikers",
  "streipïog": "striped",
  "stwffin": "stuffing",
  "sur": "sour",
  "swnio": "to sound",
  "swyddogol": "official",
  "swynol": "charming",
  "sychder": "drought, dryness",
  "sychedig": "thirsty",
  "sydyn": "sudden",
  "syllu": "to stare",
  "syllu’n syn": "to gaze in amazement",
  "sylw": "attention, remark",
  "sylwadau": "remarks",
  "sylweddoli": "to realise",
  "symbol": "symbol",
  "symbolau": "symbols",
  "synnu": "to surprise, to be surprised",
  "synnwyr cyffredin": "common sense",
  "syrcas": "circus",
  "syrcasau": "circuses",
  "syrthio": "to fall (North Wales)",
  "system": "system",
  "systemau": "systems",
  "tafodiaith": "dialect",
  "tafodieithoedd": "dialects",
  "tagfa": "traffic jam",
  "tagfeydd": "traffic jams",
  "tagu": "to splutter, to choke",
  "tâl": "payment",
  "taliadau": "payments",
  "talaith": "state",
  "taleithiau": "states",
  "talcen": "forehead",
  "talcenni": "foreheads",
  "taleb": "voucher",
  "talebau": "vouchers",
  "talentog": "talented",
  "tâp": "tape",
  "tapiau": "tapes",
  "taran": "thunder",
  "taranau": "thunder",
  "targed": "target",
  "targedau": "targets",
  "tarten": "tart",
  "tartenni": "tarts",
  "tasg": "task",
  "tasgau": "tasks",
  "tawelu": "to become quiet, to calm down",
  "teg": "fair",
  "teimlad": "feeling",
  "teimladau": "feelings",
  "teip": "type",
  "teipiau": "types",
  "telynor": "male harpist",
  "telynorion": "harpists",
  "telynores": "female harpist",
  "telynoresau": "female harpists",
  "tennyn": "lead",
  "testun": "subject, text",
  "testunau": "subjects, texts",
  "tir": "land, ground",
  "tiroedd": "lands, grounds",
  "to": "roof",
  "toeon": "roofs",
  "toddi": "to melt",
  "top": "top",
  "topiau": "tops",
  "torf": "crowd",
  "torfeydd": "crowds",
  "toriad": "cut",
  "toriadau": "cuts",
  "tortsh": "torch",
  "tortsys": "torches",
  "trac": "track",
  "traciau": "tracks",
  "traddodiad": "tradition",
  "traddodiadau": "traditions",
  "traethawd": "essay",
  "traethodau": "essays",
  "trafnidiaeth": "transport",
  "traws gwlad": "cross country",
  "trefn": "order",
  "trefniad": "arrangement",
  "trefniadau": "arrangements",
  "trin": "to treat",
  "triniaeth": "treatment",
  "triniaethau": "treatments",
  "tristwch": "sadness",
  "troellog": "twisty, windy",
  "trwchus": "thick",
  "trwm ei glyw": "hard of hearing",
  "trwm ei chlyw": "hard of hearing",
  "trwydded": "licence",
  "trwyddedau": "licences",
  "trysor": "treasure",
  "trysorau": "treasures",
  "tsieina": "China",
  "twlc": "sty",
  "tylciau": "sties",
  "twrist": "tourist",
  "twristiaid": "tourists",
  "twristaidd": "tourist (adj.)",
  "twymo": "to heat (up)",
  "tŷ pâr/semi": "semi-detached house",
  "tai pâr/semi": "semi-detached houses",
  "tylwythen deg": "fairy",
  "tylwyth teg": "fairies",
  "tymheredd": "temperature",
  "tyn(n)": "tight",
  "tyrfa": "crowd",
  "torfeydd": "crowds",
  "tyst": "witness",
  "tystion": "witnesses",
  "tywyllu": "to grow dark",
  "undeb": "union",
  "undebau": "unions",
  "undydd": "one-day",
  "unigolyn": "individual",
  "unigolion": "individuals",
  "uno": "to unite",
  "uwchben": "above",
  "ward": "ward",
  "wardiau": "wards",
  "wedi blino’n lân": "exhausted",
  "wrth fy modd": "in my element",
  "wythnosol": "weekly",
  "y cant": "per cent",
  "y pen": "per head",
  "y rhain": "these",
  "y rhan fwya(f)": "the majority",
  "y wladfa": "the colony (usually Patagonia)",
  "ymateb": "response",
  "ymatebion": "responses",
  "ymchwil": "research",
  "ymddangos": "to appear",
  "ymddeoliad": "retirement",
  "ymddeoliadau": "retirements",
  "ymddiried (yn)": "to trust (in)",
  "ymddiswyddo": "to resign",
  "ymdrech": "effort",
  "ymdrechion": "efforts",
  "ymestyn": "to stretch",
  "ymgeisio (am)": "to apply (for)",
  "ymhen": "within (time)",
  "ymhlith": "amongst",
  "ymladd": "to fight",
  "ymlaen llaw": "beforehand",
  "ymuno (â/efo)": "to join",
  "yn bennaf": "mainly",
  "yn enwedig": "especially",
  "yn erbyn": "against",
  "yn fuan": "soon",
  "yn fyw ac yn iach": "alive and kicking",
  "yn hollol": "completely, exactly",
  "yn ogystal â": "as well as, in addition to",
  "yn ôl pob sôn": "apparently",
  "yn syth bin": "immediately",
  "ynni": "energy",
  "yr ariannin": "Argentina",
  "yr unol daleithiau": "the United States",
  "ysbryd": "ghost, spirit",
  "ysbrydion": "ghosts, spirits",
  "ysgol": "ladder (South Wales)",
  "ysgolion": "ladders (South Wales)",
  "ystôl": "ladder (North Wales)",
  "ystolion": "ladders (North Wales)",
  "ysgrifen": "handwriting",
  "ysgrifennydd": "secretary",
  "ysgrifenyddion": "secretaries",
  "ysgwyd": "to shake",
};
