// Canolradd Vocabulary
const canolraddGlossary = {
// Uned 1
  "cymdeithas": "society",
  "cymdeithasau": "societies",
  "nant": "stream, creek",
  "nentydd": "streams, creeks",
  "perthynas": "relative",
  "perthnasau": "relatives",
  "ward": "ward",
  "wardiau": "wards",
  "agoriad": "opening",
  "agoriadau": "openings",
  "arweinydd": "conductor",
  "arweinyddion": "conductors",
  "claf": "patient",
  "cleifion": "patients",
  "digwyddiad": "event",
  "digwyddiadau": "events",
  "gwahaniaeth": "difference",
  "gwahaniaethau": "differences",
  "oedran": "age",
  "oedrannau": "ages",
  "partner": "partner",
  "partneriaid": "partners",
  "sylw": "attention, remark",
  "sylwadau": "attention, remarks",
  "busneslyd": "meddlesome, nosy",
  "lwcus": "lucky",
  "cyfarch": "to greet",
  "cyflwyno": "to introduce, to present",
  "swnio": "to sound",
  "ymuno": "to join (â)",
  "ar hyn o bryd": "at the moment",
  "cyfnod clo": "lockdown",
  "gyda llaw": "by the way",
  "wrth fy modd": "in my element",
  
  //Uned 2
"bricsen": "brick",
"brics": "bricks",
"cangen": "branch",
  "canghennau": "branches",
  "cerddorfa": "orchestra",
  "cerddorfeydd": "orchestras",
  "rheol": "rule",
  "rheolau": "rules",
  "cymwusnas": "favour",
  "cymwynasau": "favours",
  "siawns": "chance",
  "siawnsiau": "chances",
  "trefn": "order, arrangement",
  "trefniadau": "orders, arrangements",
  "anhapus": "unhappy",
  "sicr": "certain",
  "swyddogol": "official",
  "talentog": "talented",
//end of red and green parts
  
};
