// Mynediad Vocabulary
const mynediadGlossary = {
  "a": "and (with Treiglad Llaes)",
  "a dweud y gwir": "to be honest",
  "abertawe": "Swansea",
  "ac ati": "et cetera",
  "actor": "actor",
  "actorion": "actors",
  "actores": "actress",
  "actoresau": "actresses",
  "achos": "because",
  "adeilad": "building",
  "adeiladau": "buildings",
  "adeiladu": "to build",
  "adeiladwr": "builder",
  "adeiladwyr": "builders",
  "adolygu": "to revise",
  "adre": "home (homeward)",
  "mynd adre": "to go home",
  "afon": "river",
  "afonydd": "rivers",
  "afreolaidd": "irregular",
  "agor": "to open",
  "agos": "near",
  "angel": "angel",
  "angylion": "angels",
  "angen": "to need, a need",
  "anghenion": "needs",
  "anghofio": "to forget",
  "anghywir": "incorrect, wrong",
  "angor": "anchor",
  "angorau": "anchors",
  "ail": "second",
  "allan": "out",
  "allwedd": "key",
  "allweddi": "keys",
  "am": "about",
  "ambiwlans": "ambulance",
  "ambiwlansys": "ambulances",
  "amgueddfa": "museum",
  "amgueddfeydd": "museums",
  "aml": "often",
  "amser": "time",
  "amser sbâr": "spare time",
  "anifail": "animal",
  "anifeiliaid": "animals",
  "anifail anwes": "pet",
  "annwyd": "a cold",
  "anwydau": "colds",
  "annwyl": "dear, beloved",
  "anodd": "difficult",
  "anrheg": "gift",
  "anrhegion": "gifts",
  "apwyntiad": "appointment",
  "apwyntiadau": "appointments",
  "ar": "on (with Treiglad Meddal)",
  "ar gael": "available",
  "ar gyfer": "for (for the purpose of)",
  "ar hyn o bryd": "at the moment",
  "ar lan": "on the banks of / on the shore of",
  "ar ôl": "after, following",
  "ar unwaith": "at once",
  "ar werth": "for sale",
  "araf": "slow",
  "arall": "other",
  "arbennig": "special",
  "archebu": "to order, to book, to reserve",
  "ardderchog": "excellent",
  "arholiad": "exam",
  "arholiadau": "exams",
  "arian": "money, silver",
  "aros": "to wait",
  "ateb": "to answer, an answer",
  "atebion": "answers",
  "athrawes": "female teacher",
  "athrawesau": "female teachers",
  "athro": "male teacher",
  "athrawon": "male teachers",
  "athro cyflenwi": "supply teacher",
  "aur": "gold",
  "awdur": "author",
  "awduron": "authors",
  "awr": "hour",
  "oriau": "hours",
  "awyren": "aeroplane",
  "awyrennau": "aeroplanes",
  "babi": "baby",
  "babis": "babies",
  "bach": "small",
  "bachgen": "boy",
  "bechgyn": "boys",
  "bag": "bag",
  "bagiau": "bags",
  "banana": "banana",
  "bananas": "bananas",
  "banc": "bank",
  "banciau": "banks",
  "bar": "bar",
  "bariau": "bars",
  "bara": "bread",
  "bargen": "bargain",
  "bargeinion": "bargains",
  "barn": "opinion",
  "barnau": "opinions",
 "beic": "bike",
  "beiciau": "bikes",
  "beic modur": "motor bike",
  "beiciau modur": "motor bikes",
  "beiro": "biro",
  "beiros": "biros",
  "bendigedig": "fantastic",
  "benthyg": "to borrow, to lend",
  "berwi": "to boil",
  "beth": "what?",
  "beth bynnag": "anyway, whatever",
  "bisged": "biscuit",
  "bisgedi": "biscuits",
  "ble": "where?",
  "blin": "angry (North Wales)",
  "blodyn": "flower",
  "blodau": "flowers",
  "blwyddyn": "year",
  "blynyddoedd": "years",
  "bod": "to be",
  "bol": "stomach",
  "bola": "stomach",
  "boliau": "stomachs",
  "bore": "morning",
  "boreau": "mornings",
  "bowlio": "to bowl",
  "braf": "fine",
  "braich": "arm",
  "breichiau": "arms",
  "brawd": "brother",
  "brodyr": "brothers",
  "brecwast": "breakfast",
  "brecwastau": "breakfasts",
  "brechdan": "sandwich",
  "brechdanau": "sandwiches",
  "bron": "nearly",
  "brws": "brush",
  "brwsys": "brushes",
  "brwsio": "to brush",
  "brysio": "to hurry",
  "buan": "soon",
  "bugail": "shepherd",
  "bugeiliaid": "shepherds",
  "bwletin": "bulletin",
  "bwletinau": "bulletins",
  "bwrdd": "table",
  "byrddau": "tables",
  "bwrw eira": "to snow",
  "bwrw glaw": "to rain",
  "bws": "bus",
  "bysiau": "buses",
  "bwyd": "food",
  "bwydydd": "foods",
  "bwydlen": "menu",
  "bwydlenni": "menus",
  "bwydo": "to feed",
  "bwyta": "to eat",
  "bwyty": "restaurant",
  "bwytai": "restaurants",
  "byd": "world",
  "bydoedd": "worlds",
  "byr": "short",
  "bys": "finger",
  "bysedd": "fingers",
  "byth": "ever, never",
  "byw": "to live",
  "cacen": "cake",
  "cacennau": "cakes",
  "cadair": "chair",
  "cadeiriau": "chairs",
  "cadw": "to keep, to reserve",
  "cadw’n heini": "to keep fit",
  "cael": "to have, to get",
  "caerdydd": "Cardiff",
  "caffi": "café",
  "caffis": "cafés",
  "calan Gaeaf": "Halloween",
  "calan Mai": "May Day",
  "camera": "camera",
  "camerâu": "cameras",
  "campfa": "gym",
  "campfeydd": "gyms",
  "cân": "song",
  "caneuon": "songs",
  "canol": "centre, middle",
  "canolfan": "centre",
  "canolfannau": "centres",
  "cant": "hundred",
  "cannoedd": "hundreds",
  "canu": "to sing",
  "capel": "chapel",
  "capeli": "chapels",
  "capten": "captain",
  "capteiniaid": "captains",
  "car": "car",
  "ceir": "cars",
  "carafán": "caravan",
  "carafanau": "caravans",
  "cardiau": "cards",
  "cariad": "love, boyfriend, girlfriend",
  "cariadon": "boyfriends, girlfriends",
  "cario": "to carry",
  "cartref": "home",
  "cartrefi": "homes",
  "caru": "to love",
  "casglu": "to collect",
  "castell": "castle",
  "cestyll": "castles",
  "cath": "cat",
  "cathod": "cats",
  "cau": "to close",
  "cawl": "soup",
  "cawliau": "soups",
  "cawod": "shower",
  "cawodydd": "showers",
  "caws": "cheese",
  "cawsiau": "cheeses",
  "ceir": "cars",
  "cefn": "back",
  "cefnau": "backs",
  "cefnder": "male cousin",
  "cefndryd": "male cousins",
  "cefnogi": "to support",
  "ceffyl": "horse",
  "ceffylau": "horses",
  "ceg": "mouth",
  "cegau": "mouths",
  "cegin": "kitchen",
  "ceginau": "kitchens",
  "ceiniog": "penny",
  "ceiniogau": "pennies",
  "cenedlaethol": "national",
  "cerdyn": "card",
  "cardiau": "cards",
  "cerdded": "to walk",
  "cerddor": "musician",
  "cerddorion": "musicians",
  "cerddoriaeth": "music",
  "ci": "dog",
  "cŵn": "dogs",
  "cig": "meat",
  "cigoedd": "meats",
  "cig eidion": "beef",
  "cig moch": "bacon",
  "cig oen": "lamb meat",
  "cinio": "dinner, lunch",
  "ciniawau": "dinners, lunches",
  "clên": "agreeable, nice (North Wales)",
  "cloc larwm": "alarm clock",
  "clociau larwm": "alarm clocks",
  "clust": "ear",
  "clustiau": "ears",
  "clwb": "club",
  "clybiau": "clubs",
  "clywed": "to hear",
  "coch": "red",
  "codi": "to get up, to lift, to pick up",
  "coeden": "tree",
  "coed": "trees",
  "coes": "leg",
  "coesau": "legs",
  "cofio": "to remember",
  "coffi": "coffee",
  "coginio": "to cook",
  "cogydd": "male cook, chef",
  "cogyddion": "cooks, chefs",
  "cogyddes": "female cook, chef",
  "côr": "choir",
  "corau": "choirs",
  "cost": "cost",
  "costau": "costs",
  "cot": "coat",
  "cotiau": "coats",
  "crac": "angry (South Wales)",
  "credu": "to believe",
  "crempog": "pancake",
  "crempogau": "pancakes",
  "criced": "cricket",
  "croeso": "welcome",
  "cryf": "strong",
  "cuddio": "to hide",
  "cur pen": "headache (North Wales)",
  "cwestiwn": "question",
  "cwestiynau": "questions",
  "cwm": "valley",
  "cymoedd": "valleys",
  "cwmni": "company",
  "cwmnïau": "companies",
  "cwrdd": "to meet",
  "cwrs": "course",
  "cyrsiau": "courses",
  "cwrw": "beer",
  "cychwyn": "to begin",
  "cyfarfod": "meeting",
  "cyfarfodydd": "meetings",
  "cyfarfod (verb)": "to meet",
  "cyfarth": "to bark",
  "cyfeiriad": "address",
  "cyfeiriadau": "addresses",
  "cyfenw": "surname",
  "cyfenwau": "surnames",
  "cyfieithu": "to translate",
  "cyflym": "fast, quick",
  "cyfnither": "female cousin",
  "cyfnitherod": "female cousins",
  "cyfrifiadur": "computer",
  "cyrifiaduron": "computers",
  "cyfweliad": "interview",
  "cyfweliadau": "interviews",
  "cyngerdd": "concert",
  "cyngherddau": "concerts",
  "cyngor": "council, advice",
  "cynghorau": "councils",
  "cylchgrawn": "magazine",
  "cylchgronau": "magazines",
  "cymaint": "so much",
  "cymdogion": "neighbours",
  "cymoedd": "valleys",
  "Cymraeg": "Welsh",
  "Cymraes": "Welshwoman",
  "Cymro": "Welshman",
  "Cymru": "Wales",
  "Cymry": "Welsh people",
  "cymryd": "to take",
  "cymydog": "neighbour",
  "cymdogion": "neighbours",
  "cymylog": "cloudy",
  "cyn": "before",
  "cynnar": "early",
  "cynnes": "warm",
  "cynnwys": "to include",
  "cyntaf": "first",
  "cyrraedd": "to arrive at, to reach",
  "cysgu": "to sleep",
  "cystadleuaeth": "competition",
  "cystadlaethau": "competitions",
  "cystadlu": "to compete",
  "cytuno": "to agree",
  "cyw iâr": "chicken (meat)",
  "chi": "you (plural/formal)",
  "chwaer": "sister",
  "chwiorydd": "sisters",
  "chwaith": "either",
  "chwarae": "to play",
  "chwaraeon": "sports",
  "chwarter": "quarter",
  "chwarteri": "quarters",
  "chwerthin": "to laugh",
  "chwith": "left",
  "da": "good",
  "da-da": "sweets (North Wales)",
  "dangos": "to show",
  "dail": "leaves",
  "dal": "to catch",
  "dallt": "to understand (North Wales)",
  "damwain": "accident",
  "damweiniau": "accidents",
  "dan": "under",
  "dannodd": "toothache",
  "dant": "tooth",
  "dannedd": "teeth",
  "darllen": "to read",
  "darn": "piece",
  "darnau": "pieces",
  "dathlu": "to celebrate",
  "dawnsio": "to dance",
  "de": "south",
  "de (right)": "right",
  "deall": "to understand",
  "dechrau": "to begin, to start",
  "defnyddio": "to use",
  "deffro": "to wake up",
  "deilen": "leaf",
  "dail": "leaves",
  "deintydd": "dentist",
  "deintyddion": "dentists",
  "del": "pretty (North Wales)",
  "derbynnydd": "receptionist",
  "derbynyddion": "receptionists",
  "dewis": "choice",
  "dewisiadau": "choices",
  "dewis (verb)": "to choose",
  "diddordeb": "interest",
  "diddordebau": "interests",
  "diddorol": "interesting",
  "diflas": "miserable, boring",
  "digon": "enough",
  "digwydd": "to happen, to occur",
  "dillad": "clothes",
  "dilledyn": "garment",
  "dim": "zero, no",
  "dim byd": "nothing",
  "dim ond": "only",
  "dinas": "city",
  "dinasoedd": "cities",
  "diod": "drink",
  "diodydd": "drinks",
  "diog": "lazy",
  "diolch": "thanks",
  "di-waith": "unemployed",
  "diwetha": "last (previous)",
  "diwrnod": "day",
  "diwrnodau": "days",
  "dod": "to come",
  "dolur gwddw": "sore throat (North Wales)",
  "dosbarth": "class",
  "dosbarthiadau": "classes",
  "drama": "play",
  "dramâu": "plays",
  "dringo": "to climb",
  "dros": "over",
  "drud": "expensive",
  "drwg": "bad",
  "drws": "door",
  "drysau": "doors",
  "duw": "God",
  "dŵad": "to come (North Wales)",
  "dweud": "to say",
  "dŵr": "water",
  "dwyn": "to steal",
  "dwyrain": "east",
  "dydd calan": "New Year’s Day",
  "dydd gwener": "Friday",
  "dydd gŵyl dewi": "Saint David’s Day",
  "dydd iau": "Thursday",
  "dydd llun": "Monday",
  "dydd mawrth": "Tuesday",
  "dydd mercher": "Wednesday",
  "dydd nadolig": "Christmas Day",
  "dydd sadwrn": "Saturday",
  "dydd sul": "Sunday",
  "dydd": "day",
  "dyddiau": "days",
  "dyfalu": "to guess",
  "dyma": "here is, this is",
  "dymuno": "to wish",
  "dyn": "man",
  "dynion": "men",
  "dyna": "there is",
  "dyna drueni!": "what a pity! (South Wales)",
  "dyna pam": "that’s why",
  "dynes": "woman (North Wales)",
  "dysgu": "to teach",
  "ddoe": "yesterday",
  "ebost": "email",
  "ebyst": "emails",
  "echdoe": "the day before yesterday",
  "edrych ar": "to watch, to look at",
  "efallai": "perhaps",
  "efo": "with (North Wales)",
  "eglwys": "church",
  "eglwysi": "churches",
  "eira": "snow",
  "eisiau": "to want",
  "eistedd": "to sit",
  "eitha": "fairly, quite",
  "ennill": "to win",
  "enw": "name",
  "enwau": "names",
  "enwog": "famous",
  "er": "although",
  "erioed": "never",
  "ers": "since",
  "ers talwm": "a long time ago (North Wales)",
  "eryr": "eagle",
  "eryrod": "eagles",
  "esgid": "shoe",
  "esgidiau": "shoes",
  "sgidiau": "shoes",
  "esgusodi": "to excuse",
  "eto": "again",
  "ewythr": "uncle",
  "ewythrod": "uncles",
  "faint": "how much, how many",
  "fel": "as, like",
  "fel arfer": "usually",
  "felly": "so, thus",
  "fi": "me",
  "fideo": "video",
  "fideos": "videos",
  "finegr": "vinegar",
  "ffair": "fair",
  "ffeiriau": "fairs",
  "ffatri": "factory",
  "ffatrïoedd": "factories",
  "ffeindio": "to find",
  "ffenest": "window",
  "ffenestri": "windows",
  "ffermio": "to farm",
  "ffermwr": "farmer",
  "ffermwyr": "farmers",
  "fferyllfa": "pharmacy",
  "fferyllfeydd": "pharmacies",
  "ffigwr": "figure",
  "ffigyrau": "figures",
  "ffilm": "film",
  "ffilmiau": "films",
  "ffisig": "medicine",
  "ffisigau": "medicines (North Wales)",
  "fflat": "flat",
  "fflatiau": "flats",
  "ffôn": "phone",
  "ffonau": "phones",
  "ffôn symudol": "mobile phone",
  "ffonio": "to phone",
  "ffordd": "way, road",
  "ffyrdd": "ways, roads",
  "ffrainc": "France",
  "ffrind": "friend",
  "ffrindiau": "friends",
  "ffrwyth": "fruit",
  "ffrwythau": "fruit(s)",
  "ffurflen": "form",
  "ffurflenni": "forms",
  "gadael": "to leave",
  "gaeaf": "winter",
  "gair": "word",
  "geiriau": "words",
  "galw": "to call",
  "gallu": "to be able to, can (South Wales)",
  "gan": "by, from (a person)",
  "gardd": "garden",
  "gerddi": "gardens",
  "garddio": "to garden",
  "garddwr": "gardener",
  "garddwyr": "gardeners",
  "garej": "garage",
  "garejis": "garages",
  "geiriadur": "dictionary",
  "geiriaduron": "dictionaries",
  "gêm": "game",
  "gemau": "games",
  "glanhau": "to clean",
  "glaw": "rain",
  "go lew": "pretty good, middling (North & West Wales)",
  "gobaith": "hope",
  "gobeithion": "hopes",
  "gobeithio": "to hope",
  "gofalus": "careful",
  "gofyn": "to ask",
  "gogledd": "north",
  "golau": "light",
  "goleuadau": "lights",
  "golchi": "to wash",
  "goleuadau traffig": "traffic lights",
  "golff": "golf",
  "gorau": "best",
  "gorfod": "to have to",
  "gorffen": "to finish, to end",
  "goriad": "key (North Wales)",
  "goriadau": "keys (North Wales)",
  "gorllewin": "west",
  "gormod": "too much",
  "gorsaf": "station",
  "gorsafoedd": "stations",
  "gwaith": "work",
  "gweithiau": "works",
  "gwallt": "hair",
  "gwan": "weak",
  "gwanwyn": "spring",
  "gwario": "to spend",
  "gwasanaeth": "service",
  "gwasanaethau": "services",
  "gweddol": "so-so",
  "gweithio": "to work",
  "gweithiwr": "worker",
  "gweithwyr": "workers",
  "gweld": "to see",
  "gwely": "bed",
  "gwelyau": "beds",
  "gwell": "better",
  "gwenu": "to smile",
  "gwers": "lesson",
  "gwersi": "lessons",
  "gwerth": "worth, value",
  "gwerthu": "to sell",
  "gwesty": "hotel",
  "gwestai": "hotels",
  "gwin": "wine",
  "gwinoedd": "wines",
  "gwir": "truth",
  "gwir neu gau": "true or false",
  "gwirion": "daft (North Wales)",
  "gwisgo": "to dress, to wear",
  "gwlad": "country",
  "gwledydd": "countries",
  "gwlad yr iâ": "Iceland",
  "gwleidydd": "politician",
  "gwleidyddion": "politicians",
  "gwlyb": "wet",
  "gwneud": "to do, to make",
  "gwobr": "prize",
  "gwobrau": "prizes",
  "gŵr": "husband, man",
  "gwŷr": "husbands, men",
  "gŵr tŷ": "house husband",
  "gwraig": "wife, woman",
  "gwragedd": "wives, women",
  "gwraig tŷ": "housewife",
  "gwrando ar": "to listen to",
  "gwreiddiol": "original",
  "gwybod": "to know",
  "gŵyl": "festival, holiday",
  "gwyliau": "festivals, holidays",
  "gwylio": "to watch",
  "gwyn": "white",
  "gwynt": "wind",
  "gwyntoedd": "winds",
  "gwyntog": "windy",
  "gyda": "with (South Wales)",
  "gyda’r nos": "in the evening",
  "gyferbyn": "opposite",
  "gyrru": "to drive",
  "gyrrwr": "driver",
  "gyrwyr": "drivers",
  "haf": "summer",
  "hafau": "summers",
  "halen": "salt",
  "ham": "ham",
  "hanes": "history",
  "hanesion": "histories",
  "hanner": "half",
  "haneri": "halves",
  "hapus": "happy",
  "haul": "sun",
  "hawdd": "easy",
  "heb": "without",
  "hedfan": "to fly",
  "heddiw": "today",
  "heddlu": "police",
  "hefyd": "also, too",
  "hel": "to collect (North Wales)",
  "help": "help",
  "helpu": "to help",
  "hen": "old",
  "hen bethau": "antiques",
  "heno": "tonight",
  "het": "hat",
  "hetiau": "hats",
  "heulog": "sunny",
  "hir": "long",
  "hoci": "hockey",
  "hoff": "favourite",
  "hoffi": "to like",
  "hogan": "girl, lass",
  "genod": "girls, lasses",
  "hogyn": "boy, lad",
  "hogiau": "boys, lads",
  "hufen": "cream",
  "hufen iâ": "ice cream",
  "hwyl": "fun, bye",
  "hwyl (goodbye)": "good-bye",
  "hwyr": "late",
  "hydref": "autumn",
  "hydref": "October",
  "hyfryd": "nice, pleasant",
  "hyn": "this",
  "hynny": "that",
  "hysbyseb": "advertisement",
  "hysbysebion": "advertisements",
  "i": "to",
  "i fyny": "up, upward",
  "i ffwrdd": "away",
  "i gyd": "all",
  "i lawr": "down, downward",
  "i mewn": "in",
  "iâ": "ice",
  "iawn": "OK, very",
  "iechyd": "health",
  "ifanc": "young",
  "isio": "to want (North Wales)",
  "iwerddon": "Ireland",
  "jam": "jam",
  "jamiau": "jams",
  "joio": "to enjoy",
  "ledled": "throughout",
  "lemon": "lemon",
  "lemonau": "lemons",
  "lerpwl": "Liverpool",
  "lico": "to like (South Wales)",
  "licio": "to like (North Wales)",
  "lifft": "lift",
  "lifftiau": "lifts",
  "lolfa": "lounge",
  "lôn": "lane",
  "lonydd": "lanes",
  "lwc": "luck",
  "lwcus": "lucky",
  "llaeth": "milk (South Wales)",
  "llais": "voice",
  "lleisiau": "voices",
  "llawen": "happy, merry",
  "llawer": "a lot",
  "llawn": "full",
  "llawr": "floor",
  "lloriau": "floors",
  "lle": "place",
  "lleoedd": "places",
  "lle (North Wales)": "where?",
  "lled": "width",
  "llefrith": "milk (North Wales)",
  "llen": "curtain",
  "llenni": "curtains",
  "llenwi": "to fill",
  "llestr": "dish",
  "llestri": "dishes",
  "llinell": "line",
  "llinellau": "lines",
  "lliw": "colour",
  "lliwiau": "colours",
  "lliw haul": "suntan",
  "lloegr": "England",
  "llong": "ship",
  "llongau": "ships",
  "llond ceg": "mouthful",
  "llongyfarchiadau": "congratulations",
  "llun": "picture",
  "lluniau": "pictures",
  "llundain": "London",
  "llwnc": "throat (South Wales)",
  "llyfr": "book",
  "llyfrau": "books",
  "llyfrgell": "library",
  "llyfrgelloedd": "libraries",
  "llyfrgellydd": "librarian",
  "llyfrgellwyr": "librarians",
  "llygad": "eye",
  "llygaid": "eyes",
  "llynedd": "last year",
  "llysfab": "stepson",
  "llys feibion": "stepsons",
  "llysferch": "stepdaughter",
  "llys ferched": "stepdaughters",
  "llysiau": "vegetables",
  "llythyr": "letter",
  "llythyrau": "letters",
  "mas": "out (South Wales)",
  "mab": "son",
  "meibion": "sons",
  "mabwysiadu": "to adopt",
  "maes": "field",
  "meysydd": "fields",
  "maes parcio": "car park",
  "mam": "mother",
  "mamau": "mothers",
  "mam faeth": "foster mother",
  "mamau maeth": "foster mothers",
  "mam-gu": "grandmother",
  "mam-guod": "grandmothers (South Wales)",
  "mam-yng-nghyfraith": "mother-in-law",
  "maneg": "glove",
  "menig": "gloves",
  "manylion": "details",
  "marchnad": "market",
  "marchnadoedd": "markets",
  "mawr": "big",
  "mêc": "make",
  "mêcs": "makes",
  "medru": "to be able to, can (North Wales)",
  "meddwl": "to think",
  "meddyg": "doctor",
  "meddygon": "doctors",
  "meddygfa": "doctor’s surgery",
  "meddygfeydd": "doctor’s surgeries",
  "mefus": "strawberries",
  "mefusen": "strawberry",
  "meindio": "to mind",
  "mêl": "honey",
  "melysion": "sweets",
  "menyn": "butter",
  "menyw": "woman (South Wales)",
  "menywod": "women (South Wales)",
  "merch": "girl, daughter",
  "merched": "girls, daughters",
  "methu": "to fail",
  "mewn": "in a",
  "mewn pryd": "in time",
  "mil": "thousand",
  "miloedd": "thousands",
  "miliwn": "million",
  "miliynau": "millions",
  "mis": "month",
  "misoedd": "months",
  "mis mêl": "honeymoon",
  "misoedd mêl": "honeymoons",
  "modryb": "aunt",
  "modrybedd": "aunts",
  "moddion": "medicine",
  "môr": "sea",
  "moroedd": "seas",
  "moron": "carrots",
  "moronen": "carrot",
  "munud": "minute",
  "munudau": "minutes",
  "mwy": "more",
  "mwynhau": "to enjoy",
  "mynd": "to go",
  "mynd â": "to take",
  "mynd am dro": "to go for a walk",
  "mynediad": "entry",
  "nabod": "to know, to recognise",
  "nadolig": "Christmas",
  "nai": "nephew",
  "neiaint": "nephews",
  "nain": "grandmother (North Wales)",
  "neiniau": "grandmothers (North Wales)",
  "nawr": "now (South Wales)",
  "neb": "nobody, no one",
  "neges": "message",
  "negeseuon": "messages",
  "neis": "nice",
  "neithiwr": "last night",
  "nes": "until",
  "nesaf": "next",
  "neu": "or",
  "neuadd": "hall",
  "neuaddau": "halls",
  "newydd": "new",
  "newyddion": "news",
  "nith": "niece",
  "nithod": "nieces",
  "niwlog": "foggy, misty",
  "nofio": "to swim",
  "nôl": "to get, to collect",
  "nos": "night",
  "nosau": "nights",
  "nos galan": "New Year’s Eve",
  "noson": "evening",
  "noswaith": "evening",
  "nosweithiau": "evenings",
  "nunlle": "nowhere (North Wales)",
  "nwy": "gas",
  "nwyon": "gasses",
  "nyrs": "nurse",
  "nyrsys": "nurses",
  "nyrsio": "to nurse",
  "o": "from",
  "o gwbl": "at all",
  "o gwmpas": "around",
  "o ‘ma": "from here, away",
  "o’r gloch": "o’clock",
  "o’r gorau": "OK, alright",
  "ochr": "side",
  "ochrau": "sides",
  "oed": "age",
  "oer": "cold",
  "ofnadwy": "terrible",
  "ola": "last, final",
  "ond": "but",
  "opera": "opera",
  "operâu": "operas",
  "oren": "orange (fruit, colour)",
  "orennau": "oranges",
  "oriawr": "watch (timepiece)",
  "os": "if",
  "os gwelwch chi’n dda": "please",
  "p’nawn": "afternoon",
  "pa": "which?",
  "pabell": "tent",
  "pebyll": "tents",
  "pacio": "to pack",
  "paent": "paint",
  "paentiau": "paints",
  "pam": "why?",
  "pan": "when",
  "paned": "cuppa",
  "paneidiau": "cuppas",
  "papur": "paper",
  "papurau": "papers",
  "papur newydd": "newspaper",
  "papurau newydd": "newspapers",
  "pâr": "pair",
  "parau": "pairs",
  "paratoi": "to prepare",
  "parc": "park",
  "parciau": "parks",
  "parcio": "to park",
  "parod": "ready",
  "parti": "party",
  "partïon": "parties",
  "pasg": "Easter",
  "pasport": "passport",
  "pasportau": "passports",
  "pasta": "pasta",
  "pawb": "everyone, everybody",
  "peidio": "to stop, to cease, to refrain",
  "peintio": "to paint",
  "peiriant": "machine",
  "peiriannau": "machines",
  "pêl": "ball",
  "peli": "balls",
  "pêl-droed": "football",
  "pell": "far",
  "pen": "head",
  "pennau": "heads",
  "pen-blwydd": "birthday",
  "penblwyddi": "birthdays",
  "pennaeth": "head, principal",
  "penaethiaid": "heads, principals",
  "pensil": "pencil",
  "pensiliau": "pencils",
  "pensiwn": "pension",
  "pensiynau": "pensions",
  "pensiynwr": "pensioner",
  "pensiynwyr": "pensioners",
  "pentref": "village",
  "pentrefi": "villages",
  "penwythnos": "weekend",
  "penwythnosau": "weekends",
  "perffaith": "perfect",
  "perfformio": "to perform",
  "person": "person",
  "personau": "persons",
  "pert": "pretty (South Wales)",
  "peswch": "cough",
  "peswch (verb)": "to cough",
  "peth": "thing",
  "pethau": "things",
  "pigyn clust": "earache (North Wales)",
  "pinc": "pink",
  "plant": "children",
  "pleidleisio": "to vote",
  "plentyn": "child",
  "plismon": "policeman",
  "plismyn": "policemen",
  "pob": "each, every",
  "pobl": "people",
  "poen": "pain",
  "poenau": "pains",
  "poeni": "to worry",
  "poeth": "hot",
  "pont": "bridge",
  "pontydd": "bridges",
  "popeth": "everything",
  "porc": "pork",
  "porffor": "purple",
  "posib": "possible",
  "post": "post",
  "postmon": "postman",
  "postmyn": "postmen",
  "prawf": "test",
  "profion": "tests",
  "pres": "money (North Wales), brass",
  "prif": "main, first, top, highest",
  "prifathro": "headmaster",
  "prifathrawon": "headteachers",
  "prifathrawes": "headmistress",
  "prifathrawesau": "headmistresses",
  "prifysgol": "university",
  "prifysgolion": "universities",
  "priod": "married",
  "priodi": "to marry",
  "problem": "problem",
  "problemau": "problems",
  "pryd": "when?",
  "prynhawn": "afternoon",
  "prynhawniau": "afternoons",
  "prynu": "to buy",
  "prysur": "busy",
  "punt": "pound (money)",
  "punnoedd": "pounds",
  "pwdin": "pudding",
  "pwdinau": "puddings",
  "pwll": "pool",
  "pyllau": "pools",
  "pwll nofio": "swimming pool",
  "pwll glo": "coal mine",
  "pwy": "who?",
  "pwysig": "important",
  "pys": "peas",
  "pysgodyn": "fish",
  "pysgod": "fish(es)",
  "radio": "radio",
  "ras": "race",
  "rasys": "races",
  "rownd": "round, around",
  "rowndiau": "rounds",
  "rŵan": "now (North Wales)",
  "rygbi": "rugby",
  "rhad": "cheap",
  "rhaglen": "programme",
  "rhaglenni": "programmes",
  "rhai": "some",
  "rhan": "part",
  "rhannau": "parts",
  "rhan-amser": "part-time",
  "rhedeg": "to run",
  "rheina": "those",
  "rheoli": "to manage, to control",
  "rheolwr": "manager",
  "rheolwyr": "managers",
  "rheolwraig": "manageress",
  "rhestr": "list",
  "rhestri": "lists",
  "rhew": "ice",
  "rhif": "number",
  "rhifau": "numbers",
  "rhwng": "between",
  "rhy": "too",
  "rhyfedd": "strange, funny, odd",
  "rhyw": "any, some",
  "rhywbeth": "something",
  "rhywle": "somewhere",
  "rhywun": "someone",
  "saesnes": "Englishwoman",
  "saeson": "English people",
  "saesneg": "English (language)",
  "sais": "Englishman",
  "sâl": "ill, sick, bad, poor",
  "salad": "salad",
  "saladau": "salads",
  "sbaen": "Spain",
  "sbâr": "spare",
  "sbectol": "spectacles, glasses",
  "sbwriel": "rubbish",
  "seiclo": "to cycle",
  "sêl cist car": "car boot sale",
  "sêls cist car": "car boot sales",
  "seren": "star",
  "sêr": "stars",
  "sesiwn": "session",
  "sesiynau": "sessions",
  "sglodion": "chips",
  "sgorio": "to score",
  "sgwennu": "to write (North Wales)",
  "siarad": "to talk",
  "siaradwr": "speaker",
  "siaradwyr": "speakers",
  "siec": "cheque",
  "sieciau": "cheques",
  "sigarét": "cigarette",
  "sigaréts": "cigarettes",
  "silff": "shelf",
  "silffoedd": "shelves",
  "silff ben tân": "mantelpiece",
  "sillafu": "to spell",
  "sinema": "cinema",
  "sinemâu": "cinemas",
  "siocled": "chocolate",
  "siocledi": "chocolates",
  "sioe": "show",
  "sioeau": "shows",
  "siôn corn": "Santa Claus",
  "siop": "shop",
  "siopau": "shops",
  "siopa": "to shop",
  "siopwr": "shopkeeper",
  "siopwyr": "shopkeepers",
  "sir": "county",
  "siroedd": "counties",
  "siwgr": "sugar",
  "siŵr": "sure",
  "siŵr o fod": "probably",
  "smwddio": "to iron",
  "staff": "staff",
  "stamp": "stamp",
  "stampiau": "stamps",
  "stondin": "stall, booth",
  "stondinau": "stalls, booths",
  "stopio": "to stop",
  "stormus": "stormy",
  "stryd": "street",
  "strydoedd": "streets",
  "sudd": "juice",
  "suddion": "juices",
  "sut": "how",
  "swnllyd": "noisy",
  "swper": "supper",
  "swperau": "suppers",
  "swydd": "job, post",
  "swyddi": "jobs, posts",
  "swyddfa": "office",
  "swyddfeydd": "offices",
  "sych": "dry",
  "syched": "thirst",
  "symud": "to move",
  "syniad": "idea",
  "syniadau": "ideas",
  "syth": "straight",
  "tabled": "tablet",
  "tabledi": "tablets",
  "taclus": "tidy",
  "tad": "father",
  "tadau": "fathers",
  "tad-cu": "grandfather (South Wales)",
  "tad-cuod": "grandfathers (South Wales)",
  "tad maeth": "foster father",
  "tadau maeth": "foster fathers",
  "tad-yng-nghyfraith": "father-in-law",
  "tadau-yng-nghyfraith": "fathers-in-law",
  "tafarn": "pub",
  "tafarnau": "pubs",
  "taflen": "leaflet",
  "taflenni": "leaflets",
  "tai": "houses",
  "taid": "grandfather (North Wales)",
  "teidiau": "grandfathers (North Wales)",
  "taith": "journey",
  "teithiau": "journeys",
  "talu": "to pay",
  "tan": "until",
  "tân": "fire",
  "tanau": "fires",
  "taro": "to hit, to strike",
  "taten": "potato",
  "tatws": "potatoes",
  "te": "tea",
  "tebyg": "similar, alike",
  "tedi": "teddy bear",
  "tegan": "toy",
  "teganau": "toys",
  "tegell": "kettle",
  "tegelli": "kettles",
  "tei": "tie",
  "teis": "ties",
  "teimlo": "to feel",
  "teithio": "to travel",
  "teledu": "television",
  "tennis": "tennis",
  "teulu": "family",
  "teuluoedd": "families",
  "teuluol": "family (as adjective)",
  "ti": "you (informal singular)",
  "tîm": "team",
  "timau": "teams",
  "tipyn": "a little, a bit",
  "tocyn": "ticket",
  "tocynnau": "tickets",
  "tomato": "tomato",
  "tomatos": "tomatoes",
  "torri": "to break",
  "torri lawr": "to break down",
  "torth": "loaf",
  "torthau": "loaves",
  "tost": "toast",
  "tost": "sick, ill (South Wales)",
  "traed": "feet",
  "traeth": "beach",
  "traethau": "beaches",
  "trafod": "to discuss",
  "tref": "town",
  "trefi": "towns",
  "trefnu": "to arrange, to organise",
  "trên": "train",
  "trenau": "trains",
  "trio": "to try",
  "trip": "trip",
  "tripiau": "trips",
    "trist": "sad",
  "tro": "turn",
  "troed": "foot",
  "traed": "feet",
  "troi": "to turn",
  "trwy": "through",
  "trwyn": "nose",
  "trwynau": "noses",
  "trydan": "electricity, electric",
  "trydydd": "third",
  "tu allan i": "outside",
  "tu fas i": "outside",
  "tua": "about",
  "tudalen": "page",
  "tudalennau": "pages",
  "twp": "stupid",
  "twym": "warm, hot (South Wales)",
  "tŷ": "house",
  "tai": "houses",
  "tŷ bach": "toilet",
  "tŷ bwyta": "restaurant",
  "tai bwyta": "restaurants",
  "tyfu": "to grow",
  "tymor": "season, term",
  "tymhorau": "seasons, terms",
  "tynnu": "to pull",
  "tynnu llun": "to take a picture; to draw a picture",
  "tywydd": "weather",
  "ugain": "twenty",
  "ugeiniau": "twenties",
  "uned": "unit",
  "unedau": "units",
  "unman": "nowhere",
  "unrhyw": "any",
  "unwaith": "once",
  "uwd": "porridge",
  "wal": "wall",
  "waliau": "walls",
  "wedi blino": "tired",
  "wedyn": "after, afterwards",
  "weithiau": "sometimes",
  "wir": "indeed",
  "wrth": "by",
  "wrth gwrs": "of course",
  "wy": "egg",
  "wyau": "eggs",
  "wyneb": "face",
  "wynebau": "faces",
  "wythnos": "week",
  "wythnosau": "weeks",
 "y baban iesu": "the baby Jesus",
  "y llynedd": "last year",
  "y we": "the web",
  "ych a fi!": "horrid, yuck!",
  "ychydig": "a little, a few",
  "yfed": "to drink",
  "yfory": "tomorrow",
  "yma": "here",
  "ymarfer": "to practise, to rehearse",
  "ymddeol": "to retire",
  "ymlacio": "to relax",
  "ymlaen": "on, ahead, forward",
  "ymolchi": "to wash (oneself)",
  "ymweld": "to visit",
  "ymweliad": "visit",
  "ymweliadau": "visits",
  "yn": "in",
  "yn barod": "already",
  "yn erbyn": "against",
  "yn ôl": "back, ago, according to",
  "yn unig": "only",
  "yna": "there, then",
  "yno": "there",
  "ynys": "island",
  "ynysoedd": "islands",
  "yr alban": "Scotland",
  "yr un": "each",
  "yr wyddfa": "Snowdon",
  "ysbyty": "hospital",
  "ysbytai": "hospitals",
  "ysbwriel": "rubbish",
  "ysgol": "school",
  "ysgolion": "schools",
  "ysgrifennu": "to write",
  "ystafell": "room",
  "ystafelloedd": "rooms",
  "ystyr": "meaning",
  "ystyron": "meanings",

  //purple text that's not in the back of the book
  "ych a fi": "yuck!",
"rhywbeth arall": "something else",
"pob lwc": "good luck",
"gyda'r nos": "in the evening",
"o'r gloch": "o'clock",
"trueni": "what a pity!",
"eitha da": "quite good",
"bobl bach": "good grief!",
"o'r gorau": "okay, all right",
"tu fas": "outside (i)",

//Colors, numbers, days from page 7, 58
  "brown": "brown",
  "du": "black",
  "glas": "blue",
  "gwyrdd": "green",
  "llwyd": "grey",
  "melyn": "yellow",
  "piws": "purple",
  "un": "one",
  "dau": "two",
  "tri": "three",
  "pedwar": "four",
  "pump": "five",
  "chwech": "six",
  "saith": "seven",
  "wyth": "eight",
  "naw": "nine",
  "deg": "ten",
  "dwy": "two (fem.)",
  "tair": "three (fem.)",
  "pedair": "four (fem.)",
  "am ddim": "free",
  "ionawr": "January",
  "chwefror": "February",
  "mawrth": "March, Tuesday",
  "ebrill": "April",
  "mai": "May",
  "mehefin": "June",
  "gorffennaf": "July",
  "awst": "August",
  "medi": "September",
  "tachwedd": "November",
  "rhagfyr": "December",

  //Top 500 words list
  "agored": "open",
  "anabledd": "disability",
  "ar-lein": "online",
  "arogli": "to smell",
  "aroglu": "to smell",
  "bawd": "thumb",
  "casáu": "to hate",
  "celtaidd": "celtic",
  "celwydd": "a lie",
  "danfon": "to send, to convey, to deliver, to forward",
  "defnyddiol": "useful",
  "doctor": "doctor",
  "holi": "to ask, to enquire",
  "llythyren": "letter (of the alphabet)",
  "mosg": "a mosque",
  "myfyrwraig": "a student (fem.)",
  "offeiriad": "a priest, a clergyman",
  "prydeinig": "British",
  "rabi": "a rabbi",
  "seisnig": "English",
  "synagog": "a synagogue",
  "teml": "a temple",
    "triniaeth": "treatment",
  "tu fewn": "inside",
};
