// Sylfaen Vocabulary
const sylfaenGlossary = {
  "acen": "accent",
  "acenion": "accents",
  "actio": "to act",
  "achos": "cause, case (legal)",
  "achosion": "causes, cases (legal)",
  "achub": "to save, to rescue",
  "adar": "birds",
  "adeilad": "building",
  "adeiladau": "buildings",
  "aderyn": "bird",
  "adloniant": "entertainment",
  "adloniannau": "entertainments",
  "adroddiad": "report",
  "adroddiadau": "reports",
  "addas": "suitable",
  "addurno": "to decorate",
  "addysg": "education",
  "aelod": "member",
  "aelodau": "members",
  "agos": "near",
  "anghytuno": "to disagree (with)",
  "angladd": "funeral",
  "angladdau": "funerals",
  "albanes": "Scottish woman",
  "albanesau": "Scottish women",
  "albanwr": "Scot",
  "albanwyr": "Scots",
  "almaen": "Germany",
  "almaeneg": "German (language)",
  "almaenes": "German woman",
  "almaenesau": "German women",
  "almaenwr": "German man",
  "almaenwyr": "Germans",
  "allwedd": "key",
  "allweddi": "keys",
  "americanes": "American woman",
  "americanesau": "American women",
  "americanwr": "American man",
  "americanwyr": "Americans",
  "amlen": "envelope",
  "amlenni": "envelopes",
  "amserlen": "timetable",
  "amserlenni": "timetables",
  "amyneddgar": "patient",
  "anabl": "disabled",
  "anfon": "to send",
  "anhygoel": "incredible",
  "anobeithiol": "hopeless",
  "antur": "adventure",
  "anturiau": "adventures",
  "anturus": "adventurous",
  "ar ben fy hun": "on my own (North Wales)",
  "ar bwys": "near (South Wales)",
  "archebu": "to book, to reserve, to order",
  "archfarchnad": "supermarket",
  "archfarchnadoedd": "supermarkets",
  "ardal": "area",
  "ardaloedd": "areas",
  "ar fai": "to blame, at fault",
  "arfordir": "coast",
  "arfordiroedd": "coasts",
  "ar fy mhen fy hun": "on my own (South Wales)",
  "arian": "money; silver",
  "arian parod": "cash",
  "ar-lein": "online",
  "arlunio": "to draw, to paint",
  "ar ran": "on behalf of",
  "arswyd": "horror",
  "ar wahân": "separate",
  "ar yr un pryd": "at the same time",
  "astudio": "to study",
  "atig": "attic",
  "atigau": "attics",
  "awr ginio": "lunch hour",
  "awyr": "air; sky",
  "balch": "proud, pleased",
  "baner": "flag, banner",
  "bardd": "poet",
  "barf": "beard",
  "bedd": "grave",
  "beicio": "cycle, ride a bicycle",
  "bioleg": "biology",
  "blasu": "taste",
  "blasus": "tasty",
  "blawd": "flour",
  "blog": "blog",
  "blogio": "blog (verb)",
  "blows": "blouse",
  "bocs bwyd": "food box",
  "boch": "cheek",
  "bochdew": "hamster",
  "bodlon": "willing, contented, satisfied",
  "boeler": "boiler",
  "bôn": "base, stem",
  "botwm": "button",
  "bresychen": "cabbage",
  "busnes": "business",
  "buwch": "cow",
  "bwced": "bucket",
  "bwcio": "book (verb)",
  "bwthyn": "cottage",
  "bwydo": "feed",
  "bwystfil": "monster",
  "byw": "alive, live",
  "bywyd": "life",
  "cadair olwyn": "wheelchair",
  "cadno": "fox",
  "cae": "field",
  "caled": "hard",
  "calon": "heart",
  "call": "sensible",
  "camp": "feat",
  "campio": "to camp",
  "cangarŵ": "kangaroo",
  "canol dydd": "midday",
  "canolog": "central",
  "canrif": "century",
  "canslo": "to cancel",
  "cantores": "female singer",
  "canwr": "singer",
  "carafán": "caravan",
  "caredig": "kind",
  "carped": "carpet",
  "cartŵn": "cartoon",
  "cas beth": "pet hate",
  "cas pensiliau": "pencil case",
  "castell": "castle",
  "castell neidio": "bouncy castle",
  "cefn gwlad": "the countryside",
  "cefndir": "background",
  "cefndiroedd": "backgrounds",
  "ceiliog": "cockerel",
  "ceisiadau": "applications",
  "ceisiau": "rugby tries",
  "ceisio": "to try, to attempt",
  "celf": "art",
  "celfi": "furniture",
  "cemeg": "chemistry",
  "cerdyn credyd": "a credit card",
  "cardiau credyd": "credit cards",
  "cerddorol": "musical",
  "cestyll": "castles",
  "cewyn": "a nappy (gwr.)",
  "cigydd": "butcher",
  "cigyddion": "butchers",
  "cimwch": "lobster",
  "cimychiaid": "lobsters",
  "cinio": "dinner", 
  "ciniawau": "dinners",
  "cinio rhost": "a roast dinner",
  "ciwb": "cube",
  "clasurol": "classical",
  "clecs": "gossip",
  "clir": "clear",
"clirio": "to clear",
"cloi": "to lock",
"coeden": "a tree", 
"coed": "trees",
"coeden deuluol": "a family tree",
"coedwig": "a forest",
"coedwigoedd": "forests",
"cofiant": "a biography",
"cofiannau": "biographies",
"cofion": "regards",
"cofion cynnes": "warm regards",
"cofrestru": "to register",
"coleg": "a college",
"colegau": "colleges",
"coll": "lost",
"colli": "to lose",
"comedi": "a comedy",
"corff": "a body",
"cyrff": "bodies",
"coridor": "a corridor",
"coridorau": "corridors",
"cornel": "a corner",
"corneli": "corners",
"coron": "a crown",
"coronau": "crowns",
"corryn": "a spider",
"corynnod": "spiders",
"cost": "a cost",
"costau": "costs",
"costio": "to cost",
"crafu": "to scrape, to scratch",
"craig": "a rock",
"creigiau": "rocks",
"cranc": "a crab",
"crancod": "crabs",
"creisionen": "a crisp",
"creision": "crisps",
"creulon": "cruel",
"croen": "skin",
"crwyn": "skins",
"croesair": "crossword",
"croeseiriau": "crosswords",
"cropian": "to crawl",
"crys": "a shirt",
"crysau": "shirts",
"crys t": "a T shirt",
"cusan": "a kiss",
"cusanau": "kisses",
"cusanu": "to kiss",
"cwch": "a boat",
"cychod": "boats",
"cwmwl": "a cloud",
"cwningen": "a rabbit",
"cwningod": "rabbits",
"cwpan": "a cup",
"cwpanau": "cups",
"cwpwrdd": "a cupboard",
"cypyrddau": "cupboards",
"cwrdd": "to meet (with/a)",
"cwrt": "court (sports)",
"cyrtiau": "courts (sports)",
"cwsmer": "a customer",
"cwsmeriaid": "customers",
"cwt": "a hut",
"cytiau": "huts",
"cwympo": "to fall",
"cwyno": "to complain",
"cydweithiwr": "a colleague",
"cydweithwyr": "colleagues",
"cydweithwraig": "a female colleague",
"cydweithwragedd": "female colleagues",
"cyfarfod": "to meet or a meeting",
"cyfeillgar": "friendly",
"cyfeirio": "to direct",
"cyfle": "an opportunity, a chance",
"cyfleoedd": "opportunities, chances",
"cyfleus": "convenient",
"cyflog": "a salary",
"cylfogau": "salaries",
"cyfreithiwr": "a solicitor",
"cyfreithwyr": "solicitors",
"cyfrwng": "a medium",
"cyfryngau": "media",
"cyffredin": "common",
"cyffrous": "exciting",
"cychoeddi": "to announce, to publish",
"cyhoeddiad": "an announcement",
"cyhoeddiadau": "announcements",
  "cylch": "a circle",
"cylchoedd": "circles",
"cylch meithrin": "a pre-school nursery",
"cylchfan": "a roundabout",
"cylchfannau": "roundabouts",
"cylchgrawn": "a magazine",
"cyclgronau": "magazines",
"cyllell": "a knife",
"cyllyll": "knives",
"cymdeithas": "a society",
"cymdeithasau": "societies",
"cymdeithas rieni": "parents' association",
"cymdeithasu": "to socialise",
"cymeriad": "a character",
"cymeriadau": "characters",
"cymreig": "Welsh",
"cymuned": "a community",
"cymunedau": "communities",
"cymylau": "clouds",
"cynffon": "a tail",
"cynffonnau": "tails",
"cynnig": "an offer",
"cynigion": "offers",
"cynulleidfa": "an audience, a congregation",
"cynulleidfaoedd": "audiences, congregations",
"cyrliog": "curly",
"cysylltiad": "a contact, a connection",
"cysylltu": "to contact, to connect (with/a)",
"cytundeb": "a contract",
"cytundebau": "contracts",
"cyw": "a chick",
"cywion": "chicks",
"cywir": "correct",
"chwarae teg": "fair play",
"chwaraewr": "a player",
"chwaraewyr": "players",
  "chwerw": "bitter",
"chwilio": "to search (am/for)",
"chwyrnu": "to snore",
"chwys": "sweat",
"chwysu": "to sweat",
"chwythu": "to blow",
"daear": "earth",
"daearyddiaeth": "geography",
"dafad": "a sheep",
"defaid": "sheep",
"dart": "a dart",
"dartiau": "darts",
"datblygu": "to develop",
"dathliad": "a celebration",
"dathliadau": "celebrations",
"dawns": "a dance",
"dawnus": "talented",
"dechreuwr": "a beginner",
"dechreuwyr": "beginners",
"derbyn": "to receive, to accept",
"derbynfa": "a reception",
"derbynfeydd": "receptions",
"dibynnu": "to depend (upon), to rely on",
"difetha": "to spoil, to destoy",
"diffodd": "to switch off, to extinguish",
"digartref": "homeless",
"digidol": "digital",
"dilyn": "to follow",
"dinas": "a city",
"dinasoedd": "cities",
"diolch byth": "thank goodness",
"diolchgar": "thankful, grateful",
"disgrifio": "to describe",
"disgwyl": "to expect",
"disgybl": "a pupil",
"disgyblion": "pupils",
"distaw": "quiet",
  "diswyddo": "to make redundant",
"diwedd": "end",
"diweddion": "ends",
"diweddar": "recent",
"dod draw": "to come over",
"dogfen": "a document",
"dogfennau": "documents",
"doli": "a doll",
"doliau": "dolls",
"doniol": "funny, comical, amusing",
"draig": "a dragon", 
"dreigiau": "dragons",
"drôr": "a drawer", 
"droriau": "drawers",
"dros": "over",
"drwm": "a drum",
"drymiau": "drums",
"dwlu": "to love, to dote upon (with ar)",
"dwylo": "hands",
"dwywaith": "twice",
"dydd": "a day",
"dyddiau": "days",
"dyddiad": "a date",
"dyddiadau": "dates",
"dyddiadur": "a diary",
"dyddiaduron": "diaries",
"dyfodol": "future",
"dyffryn": "a valley",
"dyffrynnoedd": "valleys",
"dyna i gyd": "that’s all",
"ebostio": "to email",
"egwyl": "a break, break time",
"eidal": "Italy",
"eidalaidd": "Italian",
"eidaleg": "Italian (language)",
"eidales": "Italian woman",
"eidalwr": "Italian man",
"eiliad": "a second (of time)",
"eiliadau": "seconds",
"eitem": "an item",
"eitemau": "items",
"eleni": "this year",
  "eli haul": "suncream",
"eliffant": "an elephant", 
"eliffantod": "elephants",
"elusen": "a charity",
"elusennau": "charities",
"emyn": "a hymn",
"emynau": "hymns",
"er enghraifft": "for example",
"erbyn": "by (time)",
"erbyn hyn": "by now",
"eryri": "Snowdonia",
"esbonio": "to explain",
"ewrop": "Europe",
"fest": "a vest",
"festiau": "vests",
"fyny grisiau": "upstairs",
"ffa": "beans",
"ffa pob": "baked beans",
"ffafr": "a favour",
"ffafrau": "favours",
"ffaith": "a fact",
"ffeithiau": "facts",
"ffansïo": "to fancy",
"ffantasi": "a fantasy",
"ffasiwn": "a fashion",
"ffasiynau": "fashions",
"ffasiynol": "fashionable",
"ffeithiol": "factual",
"fferi": "a ferry",
"fferis": "ferries",
"fferm": "a farm",
"ffermydd": "farms",
"ffermdy": "a farmhouse",
"ffermdai": "farmhouses",
"ffeuen": "a bean",
"ffi": "a fee",
"ffioedd": "fees",
"ffiseg": "physics",
"ffitio": "to fit",
"fforc": "a fork",
"ffordd": "a road, a way",
"ffordd osgoi": "a bypass (road)",
"ffyrdd osgoi": "bypasses",
"ffrangeg": "French (language)",
"ffrainc": "France",
"ffrances": "French woman",
"ffrancesau": "French women",
"ffrancwr": "Frenchman",
"ffrancwyr": "French(men)",
"ffres": "fresh",
"ffrio": "to fry",
"ffrog": "a dress, a frock",
"ffrogiau": "dresses, frocks",
"ffŵl": "a fool",
"ffyliaid": "fools",
"ffwrn": "an oven",
"ffyrc": "forks",
"ffyrdd": "roads, ways",
"ffyrnau": "ovens",
  "gafr": "a goat",
"gair o gyngor": "a word of advice",
"galwad": "a call",
"galwadau": "calls",
"gartre": "at home",
"geifr": "goats",
"gem": "a gem", 
"gemau": "gems",
"gemwaith": "jewellery",
"geni": "to be born",
"ger": "near",
"glân": "clean",
"glanhäwr": "a cleaner",
"glanhawyr": "cleaners",
"glo": "coal",
"glöwr": "collier",
"glowyr": "colliers",
"gofalu": "to look after, to care (am/for)",
"gog": "a Northwalian",
"gogs": "Northwalians",
"gôl": "a goal",
"goliau": "goals",
"golygfa": "a view, scenery",
"golygfeydd": "views",
"golygus": "handsome",
"gorchymyn": "a command",
"gorchmynion": "commands",
"gorffennol": "past",
"gosod": "to put, to set",
"gradd": "a degree",
"graddau": "degrees",
"gratio": "to grate",
"grawnfwyd": "cereal",
"grawnfwydydd": "cereals",
"grawnffrwyth": "a grapefruit",
"grawnffrwythau": "grapefruits",
"gris": "a step, a stair",
"grisiau": "steps, stairs",
"grŵp": "a group",
"grwpiau": "groups",
"gwaed": "blood",
"gwael": "poor (quality), not well, ill",
"gwaelod": "bottom, base",
"gwaelodion": "bases",
"gwag": "empty",
"gwahanol": "different",
"gwahoddiad": "an invitation",
"gwahoddiadau": "invitations",
"gwarchod": "to protect, to babysit",
"gwario": "to spend (money)",
"gwartheg": "cattle",
"gwawr": "a dawn",
"gwawriau": "dawns",
"gweddïo": "to pray",
"gwefan": "a website",
"gwefannau": "websites",
"gweiddi": "to shout",
"gweinidog": "a minister",
"gweindogion": "ministers",
"gweinyddol": "administrative",
"gweld eisiau": "to miss, to yearn for",
"gwella": "to improve, to get better",
"gwersyll": "a camp",
"gwersylloedd": "camps",
"gwersylla": "to camp",
"gwirfoddol": "voluntary",
"gwisg": "a costume, an uniform",
"gwisgoedd": "costumes, uniforms",
"gwisg ffansi": "fancy dress",
  "gwiwer": "a squirrel",
"gwiwerod": "squirrels",
"gwlad groeg": "Greece",
"gwnïo": "to sew",
"gwregys": "a belt", 
"gwregysau": "belts",
"gwres": "temperature, heat, heating",
"gwres canolog": "central heating",
"gwrthod": "to refuse",
"gwybodaeth": "information",
"gwych": "excellent",
"gwydr": "glass; a glass",
"gwydrau": "glasses (drinking)",
"gwydraid": "a glassful",
"gŵydd": "a goose",
"gwyddau": "geese",
"gwyddel": "Irishman",
"gwyddelod": "Irish (people)",
"gwyddeleg": "Irish (language)",
"gwyddeles": "Irish woman",
"gwyddelesau": "Irish women",
"gwyddelig": "Irish",
"gwyddoniaeth": "science",
"gŵyl San Steffan": "Boxing Day",
"gwylltio": "to lose one’s temper",
"haearn": "iron",
"hamdden": "leisure",
"hardd": "beautiful",
"heb sôn am": "not to mention",
"heibio": "past",
"heini": "fit",
"hen ffasiwn": "old-fashioned",
"heulwen": "sunshine",
"hiraeth": "longing (nostalgia)",
"hofrennydd": "a helicopter",
"hofrenyddion": "helicopters",
"holl": "all, whole",
"hollol": "complete",
"hosan": "a sock",
"hosanau": "socks",
"hunan": "self",
"hunangofiant": "autobiography",
"hunangofiannau": "autobiographies",
"hwfro": "to hoover",
"Hwntw": "a Southwalian",
"Hwntws": "Southwalians",
"hwyaden": "a duck",
"hwyaid": "ducks",
"hwylio": "to sail",
"hyd yn oed": "even",
"hyderus": "confident",
"hyfforddi": "to train",
"hyfforddiant": "training, coaching",
"hyfforddwr": "a coach, a trainer",
"hyfforddwyr": "coaches, trainers",
"hysbysebu": "to advertise",
  "iach": "healthy",
  "iaith": "language",
  "iâr": "hen",
  "isel": "low",
  "jar": "jar",
  "jeli": "jelly",
  "jirâff": "giraffe",
  "lawnt": "lawn",
  "lle": "place",
  "llew": "lion",
  "lliwgar": "colourful",
  "llosgi": "burn",
  "llwy": "spoon",
  "llwybr": "path",
  "llwynog": "fox",
  "llygoden": "mouse",
  "llythyr": "letter",
  "llywodraeth": "government",
  "mab": "son",
  "maes": "field",
  "meddwi": "get drunk",
  "merch": "girl",
  "milfeddyg": "vet",
  "mochyn": "pig",
  "modrwy": "ring",
  "mwnci": "monkey",
  "myfyriwr": "student",
  "mynydd": "mountain",
  "neidr": "snake",
  "newid": "change",
  "niwl": "fog",
  "nodyn": "note",
  "nofel": "novel",
  "oedolyn": "adult",
  "oen": "lamb",
  "olew": "oil",
  "olwyn": "wheel",
  "opsiwn": "option",
  "palu": "dig",
  "papur": "paper",
  "parsel": "parcel",
  "pasio": "pass",
  "peiriannydd": "engineer",
  "pen": "head",
  "penelin": "elbow",
  "penglin": "knee",
  "pennill": "verse",
  "peryglus": "dangerous",
  "plât": "plate",
  "pluen": "feather",
  "plymwr": "plumber",
  "pobi": "bake",
  "poced": "pocket",
  "poeth": "hot",
  "popty": "oven",
  "porthladd": "port",
  "potel": "bottle",
  "powlen": "bowl",
  "priodas": "wedding",
  "pris": "price",
  "prydferth": "beautiful",
  "pupur": "pepper",
  "pwdin": "pudding",
  "pwnc": "subject",
  "pwrs": "purse",
  "pwynt": "point",
  "pysgota": "fish",
  "pythefnos": "fortnight",
  "realiti": "reality",
  "reidio": "ride",
  "reis": "rice",
  "rysáit": "recipe",
  "rhaeadr": "waterfall",
  "rhannu": "share",
  "rheswm": "reason",
  "rhiant": "parent",
  "rhugl": "fluent",
  "rhydd": "free",
  "rhyngwladol": "international",
  "rhyw fath": "some sort",
  "rhyw bryd": "sometime",
  "safle bws": "bus stop",
  "salwch": "illness",
  "sandal": "sandal",
  "sant": "saint",
  "sbaeneg": "Spanish",
  "sbectol": "glasses",
  "sboncen": "squash",
  "sebon": "soap",
  "sedd": "seat",
  "seler": "cellar",
  "selsigen": "sausage",
  "senedd": "parliament",
  "seremoni": "ceremony",
  "sgarff": "scarf",
  "sgert": "skirt",
  "sgrin": "screen",
  "sgwrs": "conversation",
  "siaced": "jacket",
  "sianel": "channel",
  "sied": "shed",
  "sinc": "sink",
  "siomedig": "disappointed",
  "siwmper": "sweater",
  "siwt": "suit",
  "sliper": "slipper",
  "sôn": "mention",
  "sosban": "saucepan",
  "soser": "saucer",
  "stadiwm": "stadium",
  "stori": "story",
  "storm": "storm",
  "straen": "stress",
  "stumog": "stomach",
  "swil": "shy",
  "sŵn": "sound",
  "swyddog": "officer",
  "sychu": "dry",
  "sylwi": "notice",
  "syml": "simple",
  "ta beth": "anyway",
  "tacluso": "tidy",
  "tacsi": "taxi",
  "tafarnwr": "innkeeper",
  "tafod": "tongue",
  "tal": "tall",
  "taldra": "height, stature, tallness",
"tap": "a tap",
"tapiau": "taps",
"tawel": "quiet, calm",
"tebot": "a teapot",
"tebotau": "teapots",
"technegydd": "a technician",
"technegwyr": "technicians",
"technoleg": "technology",
"teigr": "a tiger",
"teigrod": "tigers",
"teipio": "to type",
"teithiwr": "a traveller",
"teithwyr": "travellers",
"telyn": "a harp", 
"elynau": "harps",
"tenau": "thin",
"tew": "fat",
"tisian": "to sneeze",
"tlawd": "poor, poverty-stricken",
"ton": "a wave",
"tonnau": "waves",
"torheulo": "to sunbathe",
"tra": "while, whilst",
"tractor": "a tractor",
"tractorau": "tractors",
"traddodiadol": "traditional",
"trafferth": "trouble, bother",
"trafferthion": "troubles",
"traffordd": "a motorway",
"traffyrdd": "motorways",
"trais": "violence",
"tramor": "overseas, abroad",
"trawiadol": "striking",
"trefnus": "organised, orderly",
"treth": "a tax",
"trethi": "taxes",
"treulio": "to spend (time)",
"triongl": "a triangle",
"trionglau": "triangles",
"troedfedd": "a foot (measurement)",
"troedfeddi": "feet (measurement)",
"trôns": "underpants",
"trowsus": "trousers",
"trwm": "heavy",
"trwsio": "to repair, to mend",
"trydanwr": "an electrician",
"trydanwyr": "electricians",
"trydar": "to tweet, to twitter",
"tu ôl": "behind",
"tun": "a tin, a can",
"tuniau": "tins, cans",
"twll": "a hole",
"tyllau": "holes",
"twmpath dawns": "a barn dance",
"twmpathau dawns": "barn dances",
"twnnel": "a tunnel",
"twnelau": "tunnels",
"twpsyn": "a silly person, a stupid person",
"twpsod": "silly people",
"tŵr": "a tower",
"tyrau": "towers",
"twrci": "a turkey",
"twrcïod": "turkeys",
"twristiaeth": "tourism",
"tŷ ar wahân": "detached house", 
"tai ar wahân": "detached houses",
"tŷ gwydr": "a greenhouse",
"tai gwydr": "greenhouses",
"tŷ pâr": "semi-detached house ",
"tai pâr": "semi-detached houses",
"tŷ teras": "a terraced house",
"tai teras": "terraced houses",
"tybed": "I wonder",
"tywel": "a towel",
"tywelion": "towels",
"tywod": "sand",
"tywyll": "dark",
"theatr": "a theatre",
"theatrau": "theatres",
"uchel": "high",
"unig": "lonely, only",
"union": "exact, direct",
"wedi’r cyfan": "after all",
"wrth fy modd": "in my element",
"wrth ochr": "by the side of",
"ŵyn": "lambs",
"ŵyr": "grandson",
"wyrion": "grandsons, grandchildren",
"wyres ": "granddaughter",
"wyresau": "granddaughters",
"ychwanegol": "additional",
"ychwanegu": "to add (to/at)",
"y dyddiau hyn": "these days",
"y lleill": "the others",
"ymarfer corff": "physical education",
"ymbarél": "umbrella", 
"ymbarelau": "umbrellas",
"ymddiheuro": "to apologise",
"ymuno": "to join (a)",
"ymweld": "to visit",
"ymwelydd": "visitor",
"ymwelwyr": "visitors",
"ymyl": "an edge, rim",
"ymylon": "edges, rims",
"yn lle": "instead of, in place of",
"yn union": "exactly, directly",
"yn y bôn": "basically",
"yn y pen draw": "eventually",
"yn ymyl": "near, beside",
"yn ystod": "during",
"y rhan fwya": "the majority",
"ysgafn": "light (of weight)",
"ysgariad": "a divorce",
"ysgariadau": "divorces",
"ysgol fabanod (ben.)": "an infant school",
"ysgolion babanod": "infant schools",
"ysgol gyfun": "a comprehensive school",
"ysgolion cyfun": "comp. schools",
"ysgol gynradd": "a primary school",
"ysgolion cynradd": "primary schools",
"ysgol uwchradd": "a secondary school",
"ysgolion uwchradd": "sec. schools",
"ysgwydd": "a shoulder",
"ysgwyddau": "shoulders",
"ysmygu": "to smoke",
"ystafell": "a room",
"ystafelloedd": "rooms",
"ystafell wydr": "a conservatory",
"ystafelloedd gwydr": "conservatories",
"ystod": "range",
"yswiriant": "insurance",
"y swistir": "Switzerland",

  //Vocab from the purple boxes that's missing from the book dictionary
  "mwy nag unwaith": "more than once",
"pam lai": "why not?",
"raid cropian cyn cerdded": "You must walk before you can run",
"yn aml": "often",
"ar ben": "on top of",
"y llall": "the other",
"bob yn ail": "every other, alternate",
"mae’n debyg": "it's likely, it seems",
"mwy neu lai": "more or less",
"materion cyfoes": "current affairs",
"o dro i dro": "from time to time",
"o'r diwedd": "at last, finally",
"cadw mewn cysylltaid": "to keep in touch",
"o'r blaen": "before",
"yn y bôn": "basically",
"o hyd": "still",
"dal y lein": "to hold the line",
"papur bro": "local Welsh paper",
"ar-lein": "online",
"lan lofft": "upstairs",
"lawr llawr": "downstairs",
"uwchben": "above",
"ar fai": "at fault",
"mynd ati": "to go about (doing something)",
"braidd": "rather",
"cymru am byth": "Wales forever!",
"oddi wrth": "from (person)",
"ar goll": "lost",
"wadi'r cyfan": "after all",
"bant â ni": "off we go",
"rhywbryd": "sometime",
  
// Vocab from Yn Ei Gwsg and various other sources
"pidyn": "dick, penis",
"cachlyd": "shitty",
"bechod": "oh, bless!",
"snichyn": "creep",
"pen pidyn": "dickhead",
"penpidyn": "dickhead",
"cwsg": "sleep (noun)",
"rhyfedd": "strange",
"drych": "mirror",
  "snichyn": "creep, horrible person, sneak",
  "snichlyd": "creepy, awful",
  "gwirion": "silly",
  "amlwg": "obvious, evident",
  "gafael": "to grab, to get hold of",
  "y ffordd anghywir": "the wrong way",
  "y ffordd gywir": "the right way",
  "rhag ofn": "(just) in case",
  "dod o hyd i": "to come across/to find",
  "methu": "fail",
  "gast": "bitch",
  "a dweud y gwir": "to tell the truth",
  "malwod": "snails",
  "blynyddoedd": "years",
  "meddai": "said",
  "malu": "to destroy",
  "tarw": "bull",
  "bag chwythu": "breathalyser",
  "diolch byth": "thank goodness",
  "gollwng": "to release, to drop",
  "stumiau": "poses",
  "chwyrnu": "to snore",
  "cyfarth": "to bark",
  "piso": "to urinate",
  "taflu": "to throw",
  "breuddwydio": "to dream",
  "maddau": "to forgive",
  "planhigion": "plants",
  "briw": "cut",
  "briwiau": "cuts",
  "anaf": "injury",
  "anafiadau": "injuries",
  "llyfu": "to lick",
  "gwaedlyd": "bloody",
  "olion": "marks",
  "dilyn": "to follow",
  "pry genwair": "worm",
  "smotyn": "spot",
  "glanio": "to land",
  "diflannu": "to disappear",
  "tennyn": "lead, leash",
  "sownd": "safe, sound, stuck",
  "troi": "to turn",
  "call": "wise",
  "difaru": "to regret",
  "fel y bedd": "as quiet as the grave",
  "ar wahân i": "apart from",
  "palmant": "pavement",
  "i gyfeiriad": "towards",
  "dwyn": "to steal",
  "ymosod": "to attack (ar)",
  "lawnt": "lawn",
  "plannu": "to plant",
  "tocio": "to prune",
  "dyrnau": "fists",
  "ers tro": "for a while",
  "balch": "glad",
  "araith": "speech",
  "cyflymder": "speed",
  "dod i bed": "to come to an end",
  "patshyn": "patch",
  "gwlân": "wool",
  "crys nos": "nightshirt",
  "blodeuog": "flowery",
  "gwyrch": "hedge",
  "penlinio": "to kneel",
  "talcen": "forehead",
  "anadlu": "to breathe",
  "plygu": "to bend, to bow",
  "gwddw": "neck",
  "garddwrn": "wrist",
  "naci tad": "not at all",
  "ysgwyd": "to shake",
  "ochneidio": "to sign",
  "hurt": "stupid, stunned",
  "milgi": "greyhound",
  "baglu": "to trip",
  "rhegi": "to swear",
  "ufudd": "obedient",
  "cyffwrdd": "to touch",
  "cymhleth": "complicated",
  "ymyrryd": "to tamper, to interfere",
  "tystiolaeth": "evidence",
  "tyst": "witness",
  "braster": "fat",
  "ardal y llynnoedd": "the Lake District",
  "merched y wawr": "Welsh equivalent of the WI",
  "bwystfil": "beast",
  "cripio": "to scratch",
  "annifyr": "unpleasant",
  "blawd": "flour",
  "egluro": "to explain",
  "fforddio": "to afford",
  "yswiriant": "insurance",
  "yn glep": "with a bang",
  "cadach": "cloth",
  "sgwrio": "to scrub",
  "rhwbio": "to rub",
  "pwyth": "stitch",
  "pwythau": "stitches",
  "druan": "poor, unfortunate",
  "haeddu": "to deserve",
  "cosb": "punishment",
  "criw o gefnogwyr": "a group of supporters",
  "llydan": "wide",
  "llachar": "bright",
  "del": "pretty",
  "llygaid llo": "pretty, dreamy eyes",
  "carreg": "stong",
  "tawelwch": "silence",
  "budr": "dirty",
  "dillad budron": "dirty clothes",
  "yn bendant": "definitely",
  "rhoi mwythau": "to pet (an animal)",
  "sloch": "splash",
  "glin": "lap",
  "grawnwin": "grapes",
  "gwelw": "pale",
  "cleisiau": "bruises",
  "ewin": "nail, fingernail",
  "ewinedd": "nails, fingernails",
  "penderfynu": "to decide",
  "cricmala": "arthritis",
  "sgrech": "scream",
  "tylluan": "owl",
  "gwenwynig": "poisonous",
  "yn beryg bywyd": "extremely dangerous",
  "cyfadde": "to admit",
  "cyfaddef": "to admit",
  "o ddifri": "seriously",
  "dall": "blind",
  "gwinllan": "vineyard",
  "dwsin": "dozen",
  "carchar": "prison",
  "difrifol": "serious",
  "trwydded": "licence",
  "slei": "sly",
  "cochi": "to blush",
  "chwip o": "fantastic, brilliant",
  "dannedd gosod": "false teeth",
  "lleol": "local",
  "cylch gwau": "knitting circle",
  "noethlymun": "naked",
  "hypnotydd": "hypnotist",
  "yn ddiweddarach": "later",
  "ailgylchu": "to recycle",
  "yn hollol": "precisely",
  "llys": "court",
  "meddw gaib": "extremely drunk",
  "cyn bo hir": "soon",
  "ffydd": "faith",
  "euog": "guilty",
  "ar flaenau ei thraed": "on her tiptoes",
  
  
  
  
};
